### ISSUE TITLE
Install GitHub zip crashes MAMP server

### ISSUE THREAD

**Issue by fretzl** [zenphoto/zenphoto#100]
I downloaded the repository zip file and tried to install on my Mac (MAMP)
Whatever I do, the server crashes with this message:

<strong>httpd stopped unexpectedly</strong>

My Apache server log shows a number of these entries:

[Tue Nov 13 18:34:06 2012] [notice] child pid 497 exit signal Segmentation fault (11)

I'm afraid this may only be me but maybe someone can reproduce this.

Btw: The Zenphoto trunk works normal.

**Comment by RolandTi** [comment]
Same problem here on two different mac with MAMP and Zenphoto 1.4.14 (fresh install).

**Comment by acrylian** [comment]
Sorry, we need more info. We actually develop on MAMP…

**Comment by RolandTi** [comment]
I tried with the zip, & the tar.gz from zenphoto.org on MAMP 4.2.1 (default htdocs directory)
Here is the apache_error.log : 
`[Fri Feb 23 15:10:42 2018] [notice] Digest: generating secret for digest authentication ...
[Fri Feb 23 15:10:42 2018] [notice] Digest: done
[Fri Feb 23 15:10:42 2018] [notice] FastCGI: process manager initialized (pid 1776)
[Fri Feb 23 15:10:42 2018] [notice] Apache/2.2.32 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.0.22 mod_ssl/2.2.32 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0 configured -- resuming normal operations
[Fri Feb 23 15:10:44 2018] [error] [client ::1] client denied by server configuration: /Applications/MAMP/htdocs/.DS_Store
[Fri Feb 23 15:10:44 2018] [error] [client ::1] File does not exist: /Applications/MAMP/htdocs/docs-assets, referer: http://localhost:8888/MAMP/?language=French
[Fri Feb 23 15:10:48 2018] [error] [client ::1] client denied by server configuration: /Applications/MAMP/htdocs/.DS_Store
[Fri Feb 23 15:10:50 2018] [notice] child pid 1792 exit signal Segmentation fault (11)
[Fri Feb 23 15:10:50 2018] [notice] child pid 1791 exit signal Segmentation fault (11)
[Fri Feb 23 15:10:50 2018] [notice] child pid 1790 exit signal Segmentation fault (11)
[Fri Feb 23 15:10:50 2018] [notice] child pid 1779 exit signal Segmentation fault (11)
[Fri Feb 23 15:14:38 2018] [notice] child pid 1879 exit signal Segmentation fault (11)
[Fri Feb 23 15:14:38 2018] [notice] child pid 1878 exit signal Segmentation fault (11)
[Fri Feb 23 15:14:38 2018] [notice] child pid 1780 exit signal Segmentation fault (11)`

And the OSX console : 
`Process:               httpd [1791]
Path:                  /Applications/MAMP/*/httpd
Identifier:            httpd
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        httpd [1755]
Responsible:           httpd [1791]
User ID:               501

Date/Time:             2018-02-23 15:10:49.825 +0100
OS Version:            Mac OS X 10.13.3 (17D102)
Report Version:        12
Anonymous UUID:        52640AF6-72BA-8B2A-169E-7DE35F35CDD7


Time Awake Since Boot: 21000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000110
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x110:
--> 
    __TEXT                 000000010a64b000-000000010a6ac000 [  388K] r-x/rwx SM=COW   [/Applications/MAMP/Library/bin/httpd]

Application Specific Information:
crashed on child side of fork pre-exec

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libdispatch.dylib             	0x00007fff67daf8d6 _dispatch_root_queue_push + 108
1   libdispatch.dylib             	0x00007fff67d9f621 _dispatch_mach_msg_send + 1582
2   libdispatch.dylib             	0x00007fff67da0237 _dispatch_mach_send_drain + 325
3   libdispatch.dylib             	0x00007fff67db565e _dispatch_mach_send_msg + 394
4   libdispatch.dylib             	0x00007fff67db606d dispatch_mach_send_with_result_and_async_reply_4libxpc + 102
5   libxpc.dylib                  	0x00007fff6809a108 _xpc_connection_enqueue + 121
6   libxpc.dylib                  	0x00007fff68099b60 xpc_connection_send_message_with_reply + 207
7   com.apple.CoreFoundation      	0x00007fff4055af45 __80-[CFPrefsSearchListSource alreadylocked_generationCountFromListOfSources:count:]_block_invoke_2 + 133
8   com.apple.CoreFoundation      	0x00007fff40583af4 -[_CFXPreferences withConnectionForRole:performBlock:] + 36
9   com.apple.CoreFoundation      	0x00007fff4055ae75 __80-[CFPrefsSearchListSource alreadylocked_generationCountFromListOfSources:count:]_block_invoke + 197
10  com.apple.CoreFoundation      	0x00007fff4055acdd -[CFPrefsSearchListSource alreadylocked_generationCountFromListOfSources:count:] + 253
11  com.apple.CoreFoundation      	0x00007fff403d92c6 -[CFPrefsSearchListSource alreadylocked_copyDictionary] + 326
12  com.apple.CoreFoundation      	0x00007fff403e117f -[CFPrefsSource copyDictionary] + 47
13  com.apple.CoreFoundation      	0x00007fff40582c1c __54-[_CFXPreferences copyDictionaryForApp:withContainer:]_block_invoke + 28
14  com.apple.CoreFoundation      	0x00007fff4055c4c9 __108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke + 297
15  com.apple.CoreFoundation      	0x00007fff4055c335 -[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:] + 341
16  com.apple.CoreFoundation      	0x00007fff40582b96 -[_CFXPreferences copyDictionaryForApp:withContainer:] + 118
17  com.apple.CoreFoundation      	0x00007fff403e10c9 __CFXPreferencesCopyCurrentApplicationState + 281
18  com.apple.CoreFoundation      	0x00007fff403e0918 _CFLocaleCopyCurrentGuts + 264
19  libintl.8.dylib               	0x000000010e7fa37f _nl_locale_name_default + 47
20  libintl.8.dylib               	0x000000010e7f60d7 guess_category_value + 87
21  libintl.8.dylib               	0x000000010e7f5512 libintl_dcigettext + 1362
22  libintl.8.dylib               	0x000000010e7efe49 libintl_dcgettext + 57
23  libintl.8.dylib               	0x000000010e7efea7 libintl_gettext + 39
24  gettext.so                    	0x000000010e7ea3dd zif_gettext + 1229
25  libphp7.so                    	0x000000010bb2be95 ZEND_DO_ICALL_SPEC_HANDLER + 229
26  libphp7.so                    	0x000000010ba64a14 execute_ex + 36
27  libphp7.so                    	0x000000010ba65526 zend_execute + 2710
28  libphp7.so                    	0x000000010b9b8d27 zend_execute_scripts + 615
29  libphp7.so                    	0x000000010b8dcc4f php_execute_script + 1615
30  libphp7.so                    	0x000000010bb9c45d php_handler + 1917
31  httpd                         	0x000000010a64c72d ap_run_handler + 109
32  httpd                         	0x000000010a64ce62 ap_invoke_handler + 418
33  httpd                         	0x000000010a68553b ap_process_request + 123
34  httpd                         	0x000000010a681693 ap_process_http_connection + 147
35  httpd                         	0x000000010a6629ed ap_run_process_connection + 109
36  httpd                         	0x000000010a662fc5 ap_process_connection + 117
37  httpd                         	0x000000010a68fee2 child_main + 1602
38  httpd                         	0x000000010a68eb6e make_child + 414
39  httpd                         	0x000000010a68ef2f perform_idle_server_maintenance + 719
40  httpd                         	0x000000010a68df5d ap_mpm_run + 1485
41  httpd                         	0x000000010a655a4e main + 3278
42  libdyld.dylib                 	0x00007fff67dd4115 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000100  rbx: 0x00007fe4bb55ce90  rcx: 0x00000000a00606ff  rdx: 0x0000000000000005
  rdi: 0x00007fffa0aca800  rsi: 0x0000000111801180  rbp: 0x00007ffee55b2b30  rsp: 0x00007ffee55b2a98
   r8: 0x0000000000000005   r9: 0x0000000000000180  r10: 0x00000000ffffffff  r11: 0x00007fe4bb500000
  r12: 0x0000000000000010  r13: 0x00007fffa0aca800  r14: 0x00007fe4bb55d190  r15: 0x0000000000000003
  rip: 0x00007fff67daf8d6  rfl: 0x0000000000000206  cr2: 0x00007fffa0afd308
  
Logical CPU:     0
Error Code:      0x020000b8
Trap Number:     133`

Thank for any help !

**Comment by acrylian** [comment]
This is really weird. I have no idea currently. Is there anything in the php errorlog? 

Which PHP version are you using and is it the latest Zenphoto? Otherwise there might be issues with PHP 7 on that release. In that case you could try the  master here from GitHub.

**Comment by acrylian** [comment]
Maybe also try to update MAMP (current is 4.4.1). It's changelog read "compatibility with 10.13 improved" for 4.2.1. Maybe that wasn't enough…

**Comment by RolandTi** [comment]
Okay, that's crazy : with the same PHP, MYSQL and ports, it's working with MAMP PRO, but not with the regular MAMP. I'm gonna send a mail to MAMP dev.

**Comment by acrylian** [comment]
Please see my comment on #1143. It must be something else…
