### ISSUE TITLE
Database question: Why is text stored in serialized arrays for single language installations?

### ISSUE THREAD

**Issue by viktorzen** [zenphoto/zenphoto#1018]
Hi, I wanted to search and replace text directly at the database level and have noticed that since several versions zenphoto stores the zenpage news varchar text content in serialized arrays even though the "multi lingual" option is turned off.

Storing text as php serialized objects in mysql has some drawbacks. Mainly that it is less portable and harder to do text operations as pointed out above.

Would it not be better to store unserialized text as before if the multi lingual option is off to reduce the complexity in the database?

See also the discussion on certain serialization in wordpress http://wpgarage.com/tips/data-portability-and-data-serialization-in-wordpress/

**Comment by acrylian** [comment]
Correct about serialized array in general but in this case no. We had it that way once. The reason is that we store serialized always is that you otherwise you would loose all multilingual content once you disable the multilingual mode and accidentally re-save anything. This was a problem in the past so it was changed to always store serialized in the first place.

Are there better ways to solve multilingual content? Probably like separate table entries per language version.  However, that would be a quite a rework of that feature including migration capability so no one looses content. So currently no changes planned.

**Comment by viktorzen** [comment]
Thx for the reply, I see the point, but I would suggest instead of storing serialized data in the single language case just fix the issue(s) you found, i.e. retain the serialized data if multi lingual was on (in order to not loose it), but otherwise for new text entered just store it unserialized. The text retrieval methods (as far as I know) already work both with serialized and unserialized text fields.

**Comment by viktorzen** [comment]
ps. I think sbillard did just that ;)

**Comment by acrylian** [comment]
Actually I don't care or look at what he does or not does. Thanks for your comment though, will consider for later.

**Comment by viktorzen** [comment]
ok, hope we can improve zenphoto together, it is really a pity imho that sbillard left the main branch ;)

**Comment by acrylian** [comment]
Well ;-) Anyway, we're working on some things behind the scenes (for now) you hopefully will like later, too ;-) Only problem is time right now…
