### ISSUE TITLE
Information disclosure in /zp-core/index.php

### ISSUE THREAD

**Issue by nheiniger** [zenphoto/zenphoto#1022]
Hello,

I've recently setup several security measures for my ZenPhoto installation and in the process I found out that on the main ZP page `/zp-core/index.php` there is a function called to display information about the current installation and the script duration. Both those information may be used by an attacker to be more precise and target an attack. On my site (latest stable version, 1.4.13) the result looks like this:
```html
</html>
<!-- zenphoto version 1.4.13 [5e8b3d9eb0fa57e294b2d88ee24f06889d18b134] THEME: zpbase (album.php) GRAPHICS LIB: PHP GD library 2.1.1-dev { memory: 96M } PLUGINS: colorbox_js hitcounter image_album_statistics rss security-logger site_upgrade tinyURL trivialSpam userAddressFields zenpage zpCaptcha  -->
<!-- Temps de traitement du script Zenphoto end :0,1305 secondes -->
```

We see the exact ZP version, the theme, the PHP GD version, all plugins and the execution time! While this can be useful for debugging purposes it should be disabled (commented out in PHP) for production.

Regards,
Nicolas

**Comment by acrylian** [comment]
This of course exists for us so we are able to support quickly because sadly a lot of people forget to tell the basic infos in the first place and cause a lot of extra questions. The often it turned out they use older installs or a  third party theme/plugin we don't support at all or anymore. So this saves us all a lot of time. Of course people should upgrade frequently anyway ;-) 

You can remove this yourself by adding `zp_remove_filter('zenphoto_information')` via a plugin or your theme's functions.php.

We will however consider to remove everything expect maybe the plain Zenphoto version.

**Comment by nheiniger** [comment]
Cool that you are considering it. I opted for an easier removal by commenting line 138 in `/zp-core/index.php`:
```php
zp_apply_filter('zenphoto_information', $_zp_script, $_zp_loaded_plugins, $_index_theme);
```

It looked like the `zp_remove_filter('zenphoto_information')` in the theme does not work (or I did not use it correctly). Anyway, I got it removed :)

**Comment by acrylian** [comment]
Sure, commenting out works as well but "hacking" core files is naturally not recommend since you have to re-do it every time. And this filter also prints generation stats of the static_html_cache if enabled.

Probably themes do not work as it is too late in the file loading order, but a class type plugin (see docs) should work.
