### ISSUE TITLE
hidden albums are shown as non admin

### ISSUE THREAD

**Issue by sammichael** [zenphoto/zenphoto#1028]
hello zenphoto team!

just updated to 1.4.14 [f5b47da52f] today.
i created some albums and hide them.
hidden sub albums are realy hidden.
but not the root folders.
testet as non admin user.

think thats a bug.
in the very past that worked i remember.

michael

ps.
thats only a problem when the galery is marked as privat when its public that issue doesn't exist

update:
found the issue - user had have rights to "view all" album
shouldn't the user see only unpublished albums when he has the right for that ?

**Comment by sammichael** [comment]
in german it is "auf alle zugreifen" means "access to all"

**Comment by acrylian** [comment]
Please use the original English terms (e.g. set Zenphoto to native English and not reverse translate) when reporting bugs to avoid confusion. 

So that's "access all" then and should be working correctly:

> Access all: Access all albums without a password. Without this right, a user can access only public ones and those checked in his managed object lists. (front and back end) (ALL_ALBUMS_RIGHTS)

To limit access to specific (top) level albums, remove this right and assign albums to the user.

**Comment by sammichael** [comment]
thx for explaination
