### ISSUE TITLE
Serilization of album-title not correct

### ISSUE THREAD

**Issue by vsnase** [zenphoto/zenphoto#1030]
I created a new album "Gänseessen 2013".

This was stored in table albums in column title as follows:
a:1:{s:5:"de_DE";s:16:"Gänseessen 2013";}

This is not correct. It must be 
a:1:{s:5:"de_DE";s:15:"Gänseessen 2013";}

I just found this when simple use unserialize($title).

It seems to be the csae that wrong counted whe useing German Umlauts.

Zenphoto version 1.4.13 [5e8b3d9eb0]

**Comment by sbillard** [comment]
Could you please provide more details on what problem is this causing? I have used these kinds of characters in my album titles with no issues. Also, the serialization is done by a PHP function so not something that zenphoto has any influence on.

But more to the point, the count is correct since it is a byte count. There are 16 bytes in "Gänseessen 2013". The strings are encoded in UTF-8 which uses double bytes for many diacritical marked letters. In ASCII (a single byte encoding) the string is "GÃ¤nseessen 2013".

**Comment by acrylian** [comment]
I am using these characters frequently as well and never noticed any issue.
