### ISSUE TITLE
Title of the photo

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1041]
I found a bug when modifying the title of a photo in admin the title displayed in url is not modified it displays the old title in the url.

**Comment by fretzl** [comment]
This is by design and because Zenphoto is file system based.
Note that the title is not the same as the filename.
When you upload an image without specific EXIF data, Zenphoto will first use the filename as the title.
Afterwards you may change the title to anything you want but the filename (and URL) stays the same.
So if you want title and filename (URL) to be the same you will also have to change the filename (which can be done on the backend as well)
