### ISSUE TITLE
Authorization to add languages

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1057]
Then I have the permission to add languages ​​to zenphoto because I am sending you an email but no answer I wish to add (Arabic, Hindi, Portuguese,Hellenic and Iranian)

Tank you

**Comment by acrylian** [comment]
Sorry, we did not receive any mail recently. Did you use the contact form on our site? 

But regardless, you don't need permission to add translations. Just use pull request via GitHub. That is actually all explained on the translation tutorial right at the beginning: http://www.zenphoto.org/news/translating-tutorial/

We welcome any translation contribution. But did you really think about maintaining or starting five translations at the same time? Starting one is already quite a bunch of work (4400+ strings to translate) but five at the same time probably will get you into serious time trouble.

**Comment by zorodimanche** [comment]
Hello acrylian thank you for your reply. No I will not translate at the same time but I will start by translating the administration panels. I have set myself the goal of translating 20 channels by days and by languages.

**Comment by acrylian** [comment]
All right, just want to make sure you know what you are about to start ;-)  However, what you translate is of course primarily the administration backend anyway as that is what mostly uses static strings translated (plus some functions used by themes and/or plugins).

**Comment by zorodimanche** [comment]
which wants to help me to translate zenphoto : https://github.com/zorodimanche/zenphoto/tree/master/zp-core/locale

**Comment by acrylian** [comment]
I will close this ticket. The best would be if you actually open separate tickets here for each translation you really plan to start and possibly assign them to yourself. Once you got anything ready you feel significant, create a pull request and we'll add it. People can then also contribute to our repo.

Frequently update your catalogs so you get all string changes and nothing outdates. Also always add your name (or names if more than one translator) and the version of the next release (now 1.4.15) to the catalog settings (assuming you use Poedit). Otherwise translations are labeled as "not current" on the backend.

**Comment by acrylian** [comment]
As mentioned: I close this ticket now. Please open separate tickets for each language you wish to translate and need help so it is clear to visitors.
