### ISSUE TITLE
Put the translation of the administration panel into another file

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1058]
Separate the translation from the administration panel and place it in another file to facilitate translation to other languages ​​because a file containing all the translation of themes, plugins administration panel ... is impossible to translate. Translate the administration panel into another file to speed up loading. Could this be done.

**Comment by acrylian** [comment]
The majority of all strings to translated is the backend anyway. But you cannot divide everything between backend, themes and plugins as some zp-core stuff like are shared on all. They all share the same translation if using official template functions, also third party themes and plugins. The Zenphoto translation file just includes everything that is included officially. 

Alot of plugins would have to be modified, especially those single file plugins without a folder and a lot of translation files would require updates. Given the over all translator activity is rather low this would primarily mean a lot of translations would not be ready.

It could be done but I don't think we should use our limited resouces on something like this that is not really necessary. 

Third party themes and plugins can have their own translation files if setup for it. Most are not but that is another topic.

**Comment by sbillard** [comment]
If your goal is simply to not translate the theme specific language strings (for which there are few compared to the administrative ones) then you can limit your translation to files that are in the zp-core folder. Presuming you are using PoEdit that would be setting the `X-Poedit-Basepath:` to that folder.

You really can't exclude the plugins folder since those primarily create language strings for their administrative pages and options. There is also some overlap with the themes since they can have their own  unique options that show on the back-end. 

Sorry that translations are such a burden. I hope that the "yuge" changes to the back-end that have been promised for a while now do not invalidate your efforts.

**Comment by acrylian** [comment]
@zorodimanche Of course no efforts will be „invalidated“ but certainly some some updates might be necessary. I certainly do know how much work a translation is.

**Comment by zorodimanche** [comment]
Is it possible to have a language file for the next version of zenphoto because @sbillard informed me that there will be changes in the backend

**Comment by acrylian** [comment]
No, sorry, because it is not ready yet and also not public for various reasons. Release date is not set either (spare time work, you know). The strings itself will not change that much and gettext is clever enough to recognize strings that moved lines even without a catalogue update. Via Poedit you will later be able to parse/update the release yourself. It also provides helpers to recognize strings already in the internal translation catalogue.

**Comment by zorodimanche** [comment]
ok, I understand

**Comment by acrylian** [comment]
Thanks!
