### ISSUE TITLE
Language Statistics

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1059]
Add in the statistics of the gallery the most used languages ​​in the backend.

**Comment by sbillard** [comment]
How would you define this? 

It could be the count of users by their preferred language or a kind of "hitcounter" of languages from accesses to the backend. This latter is likely meaningless since it is dependent on what a particular user views. Users with access to more pages will overload the statistics towards their language.

**Comment by acrylian** [comment]
If you are referring to languages used by visitors of your site you could use some analytics tool like Google Analytics or as an open source alternative like Piwik.
