### ISSUE TITLE
Limit the number of consignments zenphoto_sendmail.php

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1064]
The script sends the same message to all users who have provided an email address. You should limit the number of mail sent per second. For example, send 5 mail per second ... so as not to blacklist

**Comment by sbillard** [comment]
zenphoto_sendmail is a mail handler plugin, so if there is an issue the solution should probably be more general. What exactly list of messages are you sending that is such a large number and how are you sending them?

Anyway, if your goal is really to avoid a mail blacklist then you should not be using zenphoto_sendmail as your mail handler plugin in the first place. This plugin  uses the server's sendmail feature which is typically used for SPAM since there is no real mail account involved. You should use PHPMailer and set it up with a real mail account if you wish to avoid being tagged as a spammer.

**Comment by acrylian** [comment]
What function exactly are you referring to? zenphoto_sendmail.php itself is a mail handler for the built in server mail handler. Just like phpmailer can be setup for using an actual external mail handler.

Are you referring to the user_mailing_list plugin?? That is clearly very simple and not really meant to be used like a newsletter to inform hundreds of users. 

If you really need a kind of newsletter there are far better tools/services for that.

**Comment by zorodimanche** [comment]
Yes I am talking about user mailing list.php I use it to send mail to my users in order to inform them of the novelty there are 150 emails in total and I am afraid to be considered as spammer
Then, yes there are external services but they are paying and I prefer the zenphoto plugin.

**Comment by acrylian** [comment]
In the future please tell what you are referring to in the first place.

If you are really using the sendmail handler and have that many users that might be. Even with a queue. It has already been sugggested to use the phpmailer handler and use a real mail address/account for this. It then would be the same as if you manually send a mail to many others.. Then the mail account's server would take care of that and limit the blacklisting since it is usual that many mails are send via those.

**Comment by sbillard** [comment]
Well, the zenphoto plugin works as you have described, so if you "prefer" it you must be willing to trade off being tagged as Spamming vs. the cost of a mail account. (BTW, most hosting services come with a mail account, so you should check and be sure you do not already have the means of solving your problem.)

Anyway, to slow down the e-mails means slowing down the page response to clicking on the send mail button. If you want a delay of 30 seconds between mails, your page will not refresh seven and a half minutes. Most browsers will give up before that amount of time. You can do the math, but I suspect that any delay that would pass the SPAM test would not be tolerated by your browser.

Maybe you would be better off using something like Google Groups for your mailing list. That is what these kinds of services are designed to handle.

**Comment by zorodimanche** [comment]
I opened this post because piwigo also added this in the script : https://github.com/Piwigo/Piwigo/issues/634

**Comment by acrylian** [comment]
Generally it is not that much our concern what other systems may do or not do. But we may consider this sometime when there is time.
