### ISSUE TITLE
Optimize the location by file type

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1066]
Optimize the location by file type by putting mp3 files in a sound folder, gif files in gif folder, mp4 files, avi, webm, flv ... in a video folder and finally the jpeg, png files in An image folder.

**Comment by acrylian** [comment]
Why? This overcomplicates things unnecessary. This really overcomplicates things as a jpg is internally not different than a gif or any other file Zenphoto is setup to support via plugins (AnyFile, multimedia).
 If you like your audio, video etc. files separate from images, create separate albums to do so. The gallery is a kind of file manager. This is different than Piwigo where - unless I am mistaken - images are not in physical albums.

Also "non image" files like videos or audio can have various sidecar files. The video thumb for example or counter part formats like ogg or webm/v.

**Comment by sbillard** [comment]
Just a reminder to everyone!

Zenphoto is a file system based CMS so far as media files are concerned. That means that an album in zenphoto is identical to a folder on the server. If you really wish this organization then by all means put your media files in the appropriate album/folder.

If by some stretch of the imagination you are not referring to your web content, but to the support content in zenphoto, then perhaps you have got no clue as to what you are talking about. Your suggestion would cause a pessimization instead because the software would have to compute a separate path for each file type whereas at present it does not have to care, just know where (core, plugin, etc.) the files in general are stored.

**Comment by acrylian** [comment]
As I wrote already…
