### ISSUE TITLE
Responsive version of the basic's theme

### ISSUE THREAD

**Issue by Simounet** [zenphoto/zenphoto#1068]
Hi there,
I'm a long time user who love this project and I wanted to make a responsive version of the basic's theme. Would you be interested in that?
If you do, do you have any recommendations to do this job properly? Browser minimum compatibility? Can I use a CSS pre-processor or do you want only the result?

**Comment by acrylian** [comment]
Great, we always welcome any contribution, theme or otherwise!

However, actually the plan is to retire most of the current official themes with the next major update as they are of course are dated. We probably will only have one or two themes in the future. Also to reduce things to maintain a bit…

I would suggest you do this independently as a third party theme for now. We are always a bit picky including things officially as anyone does things differently So we decide later if we incorporate it offically.

If you like to use a preprocessor, I personally use SASS (.scss). Browser compatibility should be the usual "modern browser" but not only the latest. So float and optionally flexbox would probably be the way (I made my own small responsive grid as I find frameworks like Bootstrap often a bit too much. The planned new backend will probably more or less use Boostrap though).

**Comment by Simounet** [comment]
Ok, thanks for the precisions. I'll do that. Do you have any branch where I can look at you next main theme?

**Comment by acrylian** [comment]
No, the new theme has not even been started and development of the next major version is non public currently.

**Comment by Simounet** [comment]
Ok then, I'll do that differently. Thanks again for this amazing product!

**Comment by acrylian** [comment]
Okay, thanks, I look forward to see whatever kind of theme you may come up with. Any theme is welcome and needed.
