### ISSUE TITLE
Bug when uploading the image

### ISSUE THREAD

**Issue by zorodimanche** [zenphoto/zenphoto#1070]
Hello I have this problem again with the upload because when uploading images there is this bug. It may be time to change the script of the upload for that which display the details of progressio and it is more complete: https://blueimp.github.io/jQuery-File-Upload/

Detail : it is a jpg image that makes 800ko, PHP memory limit: 128M, MySQLi version: 10.1.21, PHP version: 7.0.6, Zenphoto version 1.4.14, Graphics support: PHP GD library bundled (2.1.0 compatible)	
    supporting: gif, jpg, jpeg, png, wbmp
![ettpor](https://cloud.githubusercontent.com/assets/25553946/24831441/a837d420-1c99-11e7-9a48-78b9260fb595.png)

**Comment by acrylian** [comment]
If I look at your screenshot there is warning about no album being selected. There is an error message for a reason. Without an album selected it will of course not work.

If you did select an album and got this message, I wonder how you got that warning because the upload page does not reload on selecting images to upload.

Also when reporting such issue please always include browser, its version and the system you are using.

The script is of course planned to be updated but since we are a few versions back we need to find time to investigate if we need to change things. (I really don't know why you are  so obsession with the upload progression, we do display a progress bar and any more details will not help on such errors … ;-)).

**Comment by zorodimanche** [comment]
Hello first of all thank you for your answer in making this error occurs randomly. Then I downloaded the image in an album I just hidden it for the cure of screen because there are names of families (private reason). The site is hosted by a free lowcost hosber: hostinger (ram and cpu very limited). My os is windows 10 and I use the browser google chrome Version 57.0.2987.133 (64-bit).

**Comment by acrylian** [comment]
Ok, I understand privacy reasons on screenshots. But please mark that clearly if screenshots do not show exaxtly what's happening. It saves us from asking unnecessary questions.

If we cannot reproduce such errors they might be "randomly". A free low cost hoster might of course always something that might interfere with a lot of things. Limited traffic, bandwidth etc. So it might be just that. I would suggest to get a proper host. Over here you can get good, usable shared webspace already for around 3 Euros/Month.

**Comment by zorodimanche** [comment]
I think you're right.
