### ISSUE TITLE
Feature suggestion: webp image compression

### ISSUE THREAD

**Issue by slaattnes** [zenphoto/zenphoto#1073]
I just stumbled across the webp image format. Even though the initial release is 6 years old, it have not been adopted much. The specs looks very promising though.

> WebP lossless images are 26% smaller in size compared to PNGs. WebP lossy images are 25-34% smaller than comparable JPEG images at equivalent SSIM quality index.

Original reference: [https://developers.google.com/speed/webp/](https://developers.google.com/speed/webp/)

**Comment by slaattnes** [comment]
After some more research FLIF - Free Lossless Image Format [http://flif.info/index.html](http://flif.info/index.html) seems even better!

**Comment by acrylian** [comment]
Probably not, sorry. These formats are not generally supported by all browsers. Only Mozilla and Chrome (naturally, since it is a Google invention…) are listed but there are also Internet Explore, Safari and others.

Also browser support is not enough. If Zenphoto should be able to process these formats natively, e.g. resizing/cropping, it also requires server side support. GD only supports the basic formats, Imagick could probably but requires that encoding support is installed natively on the server. I cannot check at the moment but I don't think it is there by default default. 

On most standard shared hosting you cannot install anything natively at all. You would need to manage your own server to do these things. Not to speak that on many shared hosts you still only have GD generally.

**Comment by slaattnes** [comment]
I see. I just have to invest in dedicated hosting. Thanks for the feedback!

**Comment by acrylian** [comment]
Also even if your server would support these, you would need a fallback for those visitors whose browsers don't. 
I would stick to the "standards" unless these formats get widely used (webp exists for some years and didn't have it's breakthrough yet).

I think you can equally good results using jpeg with proper compression (and removing meta data). Own server gets quite expensive and must really be worth it.





I just checked my own server (shared as well) and my local one. Both have Imagick but no support for any of these.

**Comment by slaattnes** [comment]
Our shared hosting do not even support imagick. The cheapest managed dedicated hosting cost around 400 euros these days though.
