### ISSUE TITLE
issue with printNewsContent()

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1085]
hi

I think there is an issue with printNewsContent(). This function is hard to understand for me, so I am not sure...
I think the function parse news content but it appears that html special characters (`&nbsp;` , `&rsquo;`) are not parsed and it may break html when printNewsContent() is used in news loop and a html special characters is on the split of the news content: so the display may be `&nbs` for example.

see my example:
![screenshot007](https://user-images.githubusercontent.com/1224809/28012163-442944f4-6565-11e7-9479-8e8401c20ba0.png)

in live here: news of the 12/7/2016
http://test.vincentbourganel.fr/news/

**Comment by acrylian** [comment]
After some scrolling I finally found the example. This appears to be an image description, right? How is that added to the news text actually? Via tinyZenpage? galleryArticle plugin? Manually?

**Comment by vincent3569** [comment]
In fact, I can't remember how I have managed this text : this an old post of my prod site.
At this moment, I am migrating my site to be compliant with Bootstrap. The issue is appeared after I added some tags in the post.
In fact, this a `&rsquo;` that is used, and of course I will change it with a simple apostrophe `'` and it solve my issue. But the issue of the function will still exist ;-).

**Comment by acrylian** [comment]
Well, the actual apostrophe should of course work. But how you created that could help to find out why this happens as that seems to be a double encoding. The tinymce texteditor does encode as well so it theoretically could be a leftover from some time.

**Comment by acrylian** [comment]
I can reproduce it.

**Comment by fretzl** [comment]
I tried to reproduce it but could not.
It must be some leftover.

**Comment by acrylian** [comment]
You have to manage that the truncation in the newsloop exactly happens on such a character. Text lenght 150 in Zenpage theme "worked" for me: 
![bildschirmfoto 2017-07-11 um 12 02 10](https://user-images.githubusercontent.com/2474309/28063250-d385a978-6630-11e7-8ac6-262801e968d6.jpg)

**Comment by acrylian** [comment]
A quick fix you can do yourself is:
Add `entity_encoding: 'raw',` to the config file of TinyMCE you are using. Then only a specific set of chars is encoded at all (see https://www.tinymce.com/docs/configure/content-filtering/#entity_encoding). Re-open the article and Tinymce will fix it so it gets saved changed. This is what ZP does if TinyMCE is disabled actually. Since nowadays everyone should be using UTF-8 that should not be an issue actually.

**Comment by thany** [comment]
> Since nowadays everyone should be using UTF-8 that should not be an issue actually.

Not completely correct though. UTF-8 should be used for storage, and for passing text around. Or rather, the encoding for that should be matched, so it might as well be UTF-16.

Rendering text to the browser is a different story. In many cases, another encoding can be far more efficient than UTF-8. Think of languages that don't use our alphabet, like Japanese or Arabic. In such cases, you can't just willy-nilly push UTF-8 into a page. The renderer (if there's such a thing in zenphoto) needs to be aware of the charset used.

**Comment by acrylian** [comment]
It was a shortened description naturally…

**Comment by sbillard** [comment]
@thany: What do you perceive the issue is with UTF-8 and languages such as Japanese? UTF-8 may not be the best choice in all cases, but it does provide for representing all these diverse character sets. UTF-16 (and UTF-32) present issues in other places, such as the database. Suddenly key strings are twice (or more) as long and MySQL, at least, has physical byte length limits that can easily be exceeded.

**Comment by thany** [comment]
@sbillard I don't. I was just defending the fact that UTF-8 is not a golden hammer.
