### ISSUE TITLE
search order parameters for news and pages items

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1104]
hi

to not forget, as told on the forum (http://forum.zenphoto.org/discussion/1409825/news-order-in-search-page#latest):
in admin>options>search, it should be search order parameters for news and pages items, as exist album and image search orde parameters.

**Comment by vincent3569** [comment]
thanks for the improvement.
it works as far I have tested it.

I re-open the ticket because, according to me, the 2 news options have to be displayed only if zenpage is enabled (as the 2 options return news/pages matches).

And to be consistant with existing options, these 4 options should take care with "Enabled Zenpage items" options.

**Comment by acrylian** [comment]
True, that would be a consistent extension I did forget because I consider Zenpage very central.

**Comment by vincent3569** [comment]
order parametrers still doesn't work with pages (I tested with 'title' and 'date', but with no effect on sort order).

**Comment by acrylian** [comment]
Just added a few changes (and there was an probably year old typo…). Please give it another try.

**Comment by vincent3569** [comment]
seems to be OK now.

there is something I am unable to see in options:
in search page, is there a way to display albums and images with the same order than albums and images orders as setted in admin pages by the admin ?

**Comment by acrylian** [comment]
If you mean just the manual order via drag&drop then you would have to set the order to "custom" and "sort_order". Of course for all expect news articles as they don't know any manual order.

The concept of an default order for search results is generally a bit problematic anyway because actually the expectation is by order by relevance (internally that is called "weight").
