### ISSUE TITLE
Issue with "Data privacy policy page" option

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1177]
hi

in admin> options> security, we can choose a zenphoto page, very well.
but these are only published pages. I think it should be all unpublished pages regardless of its level.

for my personnal needs (with zpbootstap but it works like that with many other themes), published pages are automatically added in the main menu, but I don't want to show data policy page in this menu but elsewhere in the site (probably in the footer, by adding a link to this unpublished page).

currently, the only way out is to make an unpublished "fake" page, and to have a published subpage for data policy page. but I do not find it very practical.

**Comment by acrylian** [comment]
Per se the privacy page is required to be "public" by GDPR of course ;-) The "proper" and flexible way actually would be to use the menu manager plugin and two separate menu sets for this purpose and leave it to the site owner what pages he uses in which menu space. You could implement a switch use the defaults if no menu sets are defined and otherwise the menu set. The Zenpage theme does that in a simple way.

But besides that we can of course list all pages as well and mark the unpublished ones specifically.
