### ISSUE TITLE
openstreetmap doesn't show pictures

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1197]
with latest commit, I noticed that openstreetmap doesn't show pictures.

an example using zenpage theme:
https://test.vincentbourganel.fr/20170505-voyage-new-york-city/

I also notices 2 things in my console:
```TypeError: n is undefined[En savoir plus] leaflet.js:5:49465```
and
```
Erreur dans les liens source : request failed with status 404
URL de la ressource : https://test.vincentbourganel.fr/zp-core/zp-extensions/openstreetmap/leaflet.markercluster.js
URL du lien source : leaflet.markercluster.js.map[En savoir plus]
```

**Comment by acrylian** [comment]
I see those as well. But nothing had changed since you provided your recent additions. DId it work then? If so something must have changed. Also try to remove the GoogleMap just in case those don't go side by side for some reason.

This `.map` file is a js source file which is not directly for functionality and should actually not be the cause of this issue itself. 

(There is also a warning aboout missing google maps API keys on your site):

**Comment by vincent3569** [comment]
I disabled googlemap plugin, but nothing changes.
as far I can remember, I update some leaflet components, but after tests on my test site.
I will try with previous release, in case of...

**Comment by acrylian** [comment]
> I update some leaflet components, but after tests on my test site.

Well, that was then probably the wrong order ;-)

**Comment by vincent3569** [comment]
I have manually upgrade components on my test site from older release
now it works on my test site.
I will check the commits as soon as possible

**Comment by acrylian** [comment]
Thanks, appreciated!

**Comment by vincent3569** [comment]
fixed by https://github.com/zenphoto/zenphoto/commit/a11acc46637a54ed9e18796e5d34716d7a4d9e6b
