### ISSUE TITLE
openstreetmap extention with a large amount of photos

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1221]
I have a large amount of photos and have written this in my own multiple_layout *.php file. So I have a Fotomap with all photos.
https://github.com/mebels/zenphoto-osm-fotomap

There is a problem. At every, really every page view there is a database query of all photos. This will take up to several minutes. And it is very stressful for the server.

For now, I've just found a solution where I write the $geodata array/object into a *.js file with variable (file_put_contents in another multiple_layout *.php file), and embed that *.js file in HTML , Then I simply inserted the JavaScript code from Leaflet hardcoded and assigned the variable.
In addition, I have designed the fitBounds as an array in a file with variable and embedded by HTML, and assigned the variable.

It's a simple solution, just for me. Here is a suggestion:

As a final solution, it would be useful to make the extension as the sitemap extension. So that the *.js files can be updated if necessary.

The solution does not have to be realized in the existing extension. An extra extension only for a Fotomap would be nice too.

Unfortunatelly i have no time.

**Comment by acrylian** [comment]
> Unfortunatelly i have no time.

Same here. So we would welcome you contribute that as a third party extension especially since you need it. Btw, @vincent3569 has provide a tutorial for basically the same thing: https://www.vincentbourganel.fr/news/map-of-geo-localized-pictures/

**Comment by kochs-online** [comment]
> At every, really every page view there is a database query of all photos. This will take up to several minutes. And it is very stressful for the server.

Depending on the data you could improve your `SELECT` to only select images with GPS information (`…WHERE EXIFGPSLatitude != null AND EXIFGPSLongitude != null…`). An additional database index might increase performance as well. Of course this only helps if there is a considerable number of images **without** GPS data that can be omitted.

Another idea to reduce database (and front end) load might be to only select a [cleverly chosen] sample of images depending on the zoom level of your map. If you're at a continental zoom level you don't care for every single image taken on that continent, I guess. Grouping them into 100 km clusters might suffice at that point. This way you would end up with a few more `SELECT`s (one for each cluster), but you would reduce the number of results drastically. In fact the number of results would be quite stable because you only need the first result from every cluster. Increasing the zoom level would reduce the clusters in size (increasing their number), but cuts away the clusters outside of the shown part of the map (decreasing their number) – so you end up with a stable number of clusters and `SELECT`s again.

P.S.: You might also want to check for visibility of the albums. :wink:

**Comment by acrylian** [comment]
There are several ways like storing the result as JSON file or the like within the cache_html folder for example and just call that. That is what I would do to lower the load. And using the static_html_cache plugin to lower load on the pages itself

Anyway, this is a quite specific usage that should be solved by a custom plugin. I will close this ticket therefore.
