### ISSUE TITLE
Menu Manager : missing gallery index

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1222]
hi
I try to implement menu_manager in my theme (zpBootstrap and zpArdoise).
I think "gallery index" is missing in the list of posible menus items.
I can add a link to an album, or the list of all albums of the gallery, but not a basic link to the gallery.

thanks in advance

**Comment by acrylian** [comment]
There is actually a "gallery index":
![Bildschirmfoto 2019-03-28 um 07 37 08](https://user-images.githubusercontent.com/2474309/55135594-68ca2580-512c-11e9-9b58-686b64599afa.jpg)

Do you actually mean `index.php` vs `gallery.php` since traditionally/originally `index.php` was/is the gallery index as well?

**Comment by vincent3569** [comment]
maybe i'm blind or very tired.
I havn't seen `Gallery index` item.

**Comment by acrylian** [comment]
> maybe i'm blind or very tired.

Yeah, I know that ;-) But besides that I will take a look to cover both index and gallery index as default items.

**Comment by vincent3569** [comment]
I had a too quick ansver :-(
Yes I need to have both `index of site` and `index of gallery`

**Comment by vincent3569** [comment]
another thing, maybe linked with missing `gallery index` item.

I tried to add `gallery index` by using `custom theme page`.
I have the right item menu but in that case, the link is wrong:
I have the following link `https://domaine_name/page/gallery` despite the rewrite token `_GALLERY_INDEX_    gallery` and rewrite rule ` Define %GALLERY_INDEX%    gallery`.

**Comment by acrylian** [comment]
Possibly an old hardcoded value somewhere. Will take a look

**Comment by acrylian** [comment]
It is actually correct as you added it as a custom page which has this link. The menu does not "know" that this is a special custom page. That's why there is (or should be) a separate menu item.

**Comment by acrylian** [comment]
I checked and this applies to all known custom pages. To honor custom rewrite rules they would need their own menu item.  

The custom page selector is confusing anyway since it lists all files in a theme no matter if they make sense like themeoptions, functions, partial layout pages like footer, image.php or even album.php which has a separate menu item type already. 

It is hard to filter that list since it could exclude, well, custom pages we don't know of. So I am thinking of removing that selector and adding individual menu item types  for these pages that make sense to link to:

- archive
- contact
- favorites
- register_user
- search

**Comment by acrylian** [comment]
Try the support build. The gallery link should now cover rewrite rules and there is a new "home page" menu item type which naturally may be the same as the gallery index (notes have been added to both item types). The custom page addition should now also work as expected regarding the title.
