### ISSUE TITLE
no confirmation message when delete a theme

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#1225]
hi,

as told in the title, there is no confirmation message when we delete a 3rd party theme.
there is that kind of message of most delete action (album, page, custom menu set...).
according to me, that message is missing in that case.

**Comment by acrylian** [comment]
Thanks, was indeed missing.

**Comment by vincent3569** [comment]
it works, but there is something strange now: buttons doesn't have the same size !

![ScreenShot012](https://user-images.githubusercontent.com/1224809/55388544-c6e37800-5533-11e9-8b1e-d9afd8aa7a18.png)

**Comment by acrylian** [comment]
Yes, but that is cosmetic and not related to this issue. I cleaned up some weird html decisions made way back. There were a lot of links that had a script directing to an url that also could have been used directly. Which I changed now as it makes no sense. Some buttons were `<a>` elements that actually should have been `<button>` elements because they only executed a JS function. If it leads nowhere it is a button and not a link. I have just not adjusted the CSS for this yet.
