### ISSUE TITLE
sort order and album thumb break by move album

### ISSUE THREAD

**Issue by mebels** [zenphoto/zenphoto#1226]
Zenphoto version 1.5 (Official build)
PHP version: 7.1.27
 Graphics support: PHP Imagick library 3.4.3
ImageMagick 6.9.10-33 Q16 x86_64 2019-03-11 https://imagemagick.org	
    supporting: bmp, bmp2, bmp3, gif, gif87, jpeg, jpg, png, png24, png32, png8, tiff, tiff64	
PHP memory limit: 256M (Note: Your server might allocate less!)
MySQLi version: 5.5.5 

Hello,
There are two problems with move album/photos. One with album and photos from a migration and one with newly created albums and photos.

1.) Album/Photos from Migration
If I move an album, the manual order of the photos and the manually set thumbnail will be lost. Saving the order and resaving the thumb before moving does not help.
https://github.com/mebels/men-to-zen-migration

2.) New album move
When I move an album, the manual order of the photos is lost.

3.) New photos move
When I move photos to an existing album with photos, the new photos are mixed between the old photos. That's a mess. The new photos are unfortunately not put to the end.

Automatic sorting does not help me, because in almost all albums manual sorting is.

**Comment by acrylian** [comment]
1.5 is not the current version. Please try at least 1.5.1 or the support build

**Comment by fretzl** [comment]
I did some moving around with albums and images and all works as expected.
Be aware that there is a difference between sorting for the back-end and sorting for the front-end

**Comment by sbillard** [comment]
Regarding the sort order of the migrated images. Your script seems to set the zenphoto sort_order field to an ascending integer.  Unfortunately this does not work so well for a sort_order in zenphoto. The sort on this field is a string sort, so such strings as '219' is sorted lower than '3'. Zenphoto insures that the sort_order value is always 3 digits so that things get sorted correctly.

I also do not see any place where you set the album sort_type to manual (or the general album sort to manual.) Likewise with the sort direction.

**Comment by acrylian** [comment]
This ticket is closed now as there has been no answer to questions for 7 days. Additionally we cannot reproduce it and it seems to be related to some custom migration script anyway.
