### ISSUE TITLE
Plugin options lost after running setup on existing installation

### ISSUE THREAD

**Issue by kochs-online** [zenphoto/zenphoto#1228]
About a week ago my hoster updated its MySQL server to a newer version and upon noticing Zenphoto (official build, version 1.5.1) required me to run setup again. Afterwards the plugin options are gone. Not only a plugin I wrote myself is affected, but also officially supported ones like GoogleMap (losing the Google API key).

I experienced this issue before (months ago), but couldn't trace it back to the setup. Now that I did I can reproduce the behavior reliably. Just enter an API key for Google Maps in the plugin options, run setup and the key is gone.

**Comment by acrylian** [comment]
Please try the support build if you haven't yet.

**Comment by bic-ed** [comment]
Something strange here too, even with latest support build. I've not checked all settings in every plugin, but for instance the website field in comment form plugin switches from "show" to "require" after running installation.

**Comment by acrylian** [comment]
It's always `setOptionDefault()`. These options are set by setup by loading a plugin and instantiating the option interface class. And the option interface constructor sets the default options using that.

**Comment by bic-ed** [comment]
I'm not sure I did understand what you mean. Are you saying that plugin's settings are always restored to their default values during setup if a default value exists?

**Comment by acrylian** [comment]
No, setup would set all options to their defaults via setOptionDefault() if not already set. Apparently here something goes wrong. No idea what right now because there is no default of "require" for the web option in comment_form (to stay on this one reproducable example). So no idea why it is set to require yet. Probably one tiny things somewhere buried…

**Comment by bic-ed** [comment]
Ok, then for option already set 'setOptionDefault()' should not have any effect. That's why I suppose the issue is elsewhere. On the other hand, setup switches from "show" to "required" the website field in comment form, that is not the default option at all.

**Comment by acrylian** [comment]
> On the other hand, setup switches from "show" to "required" the website field in comment form, that is not the default option at all. 

Yes, as I noticed as well this adds to the confusion.

**Comment by acrylian** [comment]
I found where this happens. It is indeed not `setOptionDefault()`. For some reasons these options are set to "required" in `/setup/setup-option-defaults.php` via a plain `setOption()`. That does not even honor that there are three values and sets to required when set to `1` which means `show`. 

I can only assume this is forgotten legacy code from before comments were plugin based and this option perhaps was boolean indeed (I don't remember). 

I will go through that script to find more forgotten plugin options as it actually should not set any at all (unless for some reasons needed I cannot think of right now).

**Comment by bic-ed** [comment]
I've found the code you are talking about (for comment form only) but keep in mind that a similar issue (not preserving options already set) also affects other plugins. For instance, the link for Button: Learn more - URL in cookieconsent plugin is empty after setup, even if it was correctly filled before. As for the API key of Google maps plugin, as reported by @kochs-online .

**Comment by acrylian** [comment]
I found similar code for the RSS and menu_manager. 

I could direclty reproduce the comment_form issue but I cannot reproduce the GoogleMap Api key or the cookie consent issue. The values stick here when I test.

**Comment by bic-ed** [comment]
Have you those plugin enabled? I'm asking because I tested that if they are disabled then the values are preserved for me too.

**Comment by acrylian** [comment]
Yes, of course enabled.

**Comment by bic-ed** [comment]
Ouch! I can reproduce the issue on both local and remote server.

**Comment by acrylian** [comment]
That's unfortunate. I may have asked before: Does your server have cURL? Because this happened a lot with the old (now fallback) way of setting options in  setup.

**Comment by kochs-online** [comment]
I just checked: cURL is enabled for me. Version is 7.38.0.

**Comment by bic-ed** [comment]
Here too, enabled on local (7.51.0  )and remote (7.38.0 )

**Comment by acrylian** [comment]
Thanks, then we can exclude that at least. Now we have to find why this still does not happen to all. @fretzl also cannot reproduce it so far as he just told me.

**Comment by vincent3569** [comment]
as discussed with Malte, I have some options lost during setup.
all options about map credentials of plugin openstreetmap  are reseted after setup.

**Comment by acrylian** [comment]
We really believed our changes regarding the setup request did fix this. I just tried on our test site on our server and there indeed the same happens. It does not really help that it does not locally. So something is different.

**Comment by vincent3569** [comment]
a good point: the problem does exist, it is reproducible on different servers. so we did not dream.
maybe add a debug on sql queries during setup?

**Comment by acrylian** [comment]
Of course I will do that as soon as I get the time to do so.

**Comment by acrylian** [comment]
A quick update what I could find out on the live test site:
The isse seems to be related to options that don't have any `setOptionDefault()` calls. This is the case for the api_key option of GoogleMaps I initially could reproduce the issue with.

So I added `setOptionDefault()` that set those option to `''` (empty string) for that option the plugin. 

1. Save those options
1. Run setup -> Options are cleared
3. Set options again
4. Run setup -> Options stick and do so from then on

I could reproduce the same behaviour with the three button options of cookieconsent and the API key options of openstreetmap.

Still don't understand it fully because the option still sticks afterwards even if I then remove those setOptionDefault() calls again. The database entries are the same regardless if set via default options or via option save manually. It "should" not make any difference for the default option setting. Probably still a details somewhere I don't spot yet…

Again, this issue does not appear on any local test site so it is still hard to reproduce or find out. Anyway please try this as well.

**Comment by bic-ed** [comment]
Actually I did try this trick a few days ago, but I didn't realize it works! Probably I made something wrong, because I've tried again now and it really worked. I can also confirm that removing the setOptionDefault() line and rerunning setup the option is not cleared again.

**Comment by acrylian** [comment]
Thanks for at least confirming this behaviour.

> *Or may be it was beacause I tried only once the first time?

Perhaps. There must be a difference somehow although there shouldn't be any… Probably a good idea to always set default options so they are prepared in any case…

**Comment by bic-ed** [comment]
> Thanks for at least confirming this behaviour.

Yesterday I've also tried to play with setup scripts to find where the bug is, but no luck for me. then I had to temporary give up for many reasons

**Comment by vincent3569** [comment]
Hi,
so I understand why the akismet key is not removed on my plugin...

```
	function __construct() {
		setOptionDefault('Akismet_key', '');
		setOptionDefault('Forgiving', 0);
	}
```

>The database entries are the same regardless if set via default options or via option save manually. It "should" not make any difference for the default option setting. Probably still a details somewhere I don't spot yet…
that why I suggest you to have debug logs for sql statements of setup.

anyway, I tried with google_map and osm plugins and your fix worked.

**Comment by acrylian** [comment]
> that why I suggest you to have debug logs for sql statements of setup.

What do you think I did? I will further investigate nevertheless.

**Comment by acrylian** [comment]
Since this issue of course bothered me especially as I could reproduce it.  So I gave it a fresh shot today and I found it finally. The issue was not in setup but within admin functions on manual saving setting a wrong creator if you have installed in the root of your domain. That's also why I couldn't reproduce it locally as that's always in subfolders. This wrong creator got the options to be deleted by a cleanup routine in setup.

I tried with a bogus plugin. Here the wrong creator (note the missing slash):

![Bildschirmfoto 2019-04-17 um 16 46 14](https://user-images.githubusercontent.com/2474309/56297926-8c7ffa80-6131-11e9-8e81-704def0c5027.jpg)

And here the correct one:

![Bildschirmfoto 2019-04-17 um 16 54 30](https://user-images.githubusercontent.com/2474309/56297937-91dd4500-6131-11e9-8f9b-76866e04dd4d.jpg)

Please give it a try this fixes it on our live test site even without any `setOptionDefault()`.

**Comment by bic-ed** [comment]
I probably tested too fast, before your latest commit #1128 . I'll test again now, anyway there is some weird behavior to report: after a first setup, the Learn more - URL option in cookieconsent plugin was empty again, and the actual link in frontend was filled whit the value set in Custom page url option placed in general Options > Security Tab. Then I filled again the option in cookieconsent plugin, re-run setup and the option sicked this time.

**Comment by acrylian** [comment]
Probably you had old wrong option entries with the wrong creator in the database. These do get indeed deleted. I should have mentioned that you first have to save manually to fix the creator entry in the database. The fix does not do this.

Btw, I did not encounter the issue you reported while testing the bogus plugin within /plugins and within /zp-core/zp-extensions.

**Comment by bic-ed** [comment]
Of course, I created the option before updating to latest support build! ;-)
So it should be fine now, thanks for the hard work!

**Comment by acrylian** [comment]
Okay, perhaps some browser cache fun, no idea. But hopefully this really fixes the general issue as the saving should set the right creator. And it is probably still a good idea to always set default option values even if default is empty.

**Comment by vincent3569** [comment]
>And it is probably still a good idea to always set default option values even if default is empty.

I think so.
All options are created in db, even if they have empty value.

As far I can test, it works for me.
- I reseted all relevant options
- I ran a setup (all key values are empty)
- I added all key values for gmap and openstreetmap
- I ran a setup again (all key values are still here)

**Comment by acrylian** [comment]
Thanks for testing, Vincent.
