### ISSUE TITLE
Articles in Zenpage and HTM 5 tags omitted

### ISSUE THREAD

**Issue by RolandTi** [zenphoto/zenphoto#1237]
Hello,
I'm using Zenphoto 1.5.1 (but there is nothing about it in the 1.5.2 changelog),
and when I'm editing an article, Zenphoto is removing some of "modern" html tags like figure or figcaption everytime I save it.

Not very convenient :)

thanks for any support !

**Comment by acrylian** [comment]
I will take a look if these somehow slipped through. We had no ticket or report about this as far as I remember. 

Meanwhile check `Options > General > Allowed tags` what html tags (well, actually "elements" ;-)) are listed. You can add them or any element yourself following the pattern actually.

**Comment by RolandTi** [comment]
Thanks ! I added them back. I also added SUP and SUB ;-)

**Comment by acrylian** [comment]
Also if you are using TinyMCE it might also be that it clears as well independently from ZP.

SInce we have 1.5.3 coming shortly because of an serious bug in 1.5.2 I will see to add more HTML elements to the defauts. 

I would add article, section, figure, figcaption, video, audio, sub, sup. Any else we should add while we're at it?
