### ISSUE TITLE
zp_user_auth cookie disappearing

### ISSUE THREAD

**Issue by asgozzi** [zenphoto/zenphoto#1248]
The cookie seems to disappear with every click, meaning that each page change requires to re-login. I cannot access any admin menus, I am always being redirected to the login form.  
I upgraded to 1.5.4, the problem persists. I have tried with Safari, FF and Chrome as well as with private navigation.  

In the **security.log**  I have a bunch of messages like this

> 2019-07-13 16:35:12		Authorization cookie check			Failed		XXXXX

**Comment by acrylian** [comment]
Sorry, we cannot reproduce this. I assume you did check your browser cookie settings? What are the cookie setting on the Zenphoto options? You find them on Options > General > Cookies
Default settings are these:
![Bildschirmfoto 2019-07-14 um 17 41 30](https://user-images.githubusercontent.com/2474309/61185885-a6f93f80-a65e-11e9-92be-197c907f6e32.jpg)

And also Options > Security > Cookie Security (default is off).

**Comment by asgozzi** [comment]
![zenphoto](https://user-images.githubusercontent.com/24810612/68082802-5e3de000-fe21-11e9-8b0f-9308f5b1f183.png)

The issue is back.
This happens with 3 different browsers on OSX Sierra but **not** on a Windows 10 PC.  
So it seems to be related to the system. How can I debug it?

I have upgraded to v1.5.5 but that didn't change anything.

**Comment by acrylian** [comment]
We still cannot reproduce this. Did you check your browser settings? If you are using a private mode, disabled cookies or clear all data after closing the browser this is expected behaviour.

**Comment by asgozzi** [comment]
OSX version is 10.12.6  
I have cleared all navigation data and cookies in FF, still experiencing the same issue. Can something be enabled on server side to have more logs?

**Comment by acrylian** [comment]
There is a debug log of Zenphoto itself for any PHP related issues and there is your server's php error log. Also review your browser console log for any client side issues.

Also please post your complete cookie options of Zenphoto.

**Comment by Barastan** [comment]
Am having a similar problem. Fresh install of 1.5.7. Have not even fully set up Zen Photo, the admin backend kicks me and afterwards, no login possible. Security log is like this:
![image](https://user-images.githubusercontent.com/49413061/103021409-52bae600-4507-11eb-8eb4-be6bf45c86cb.png)

Happens in FF, Chrome, and Edge on Win10. Chrome Devtools reports "Refused to load the image 'https://www.dev.geniusworks.ca/favicon.ico' because it violates the following Content Security Policy directive: "default-src https://dev.geniusworks.ca/DHoganDarkArts/ 'unsafe-inline' 'unsafe-eval' img-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback" 
And 
"The Content Security Policy directive 'default-src' contains 'img-src' as a source expression. Did you mean 'default-src ...; img-src...' (note the semicolon)?"

While FF devTools reports this: (more relevant, I would think)
"Cookie “zp_user_auth” has been rejected because it is already expired.  Cookie “zenphoto_ssl” has been rejected because it is already expired."

This happens in Chrome, FF, and Edge on Windows Private windows and cookies cleared.

What admin settings would cause this effect? And, where can I turn it off in the Admin pages?

**Comment by acrylian** [comment]
Check the cookie options under the Security options. Perhaps you have not set any expiration or a too short one so they expire instantly. There should be a default but perhaps that was not set by whatever reason. I still cannot reproduce this issue in my browsers.

The favicon is for sure not related to the cooke issue and is not major issue at all. I don't even see that one on the backend. The front end normally does not set any security headers by default unless you have enabled the http_security_headers plugin which requiers that "you know what you do" as it even can break the site if not configured properly. It is off by default.

**Comment by Barastan** [comment]
@acrylian, a point I forgot to mention, and just realized, is my whole site has an SSL/https wildcard certificate. Would this make a difference in how ZP handles the cookies, or their storage?

**Comment by acrylian** [comment]
I don't think the certificate makes any difference. We use Let's Encrypt certificates on our sites (and I know a few more) without problems.
