### ISSUE TITLE
sitemap-extended produces links to the old .alb suffixed dynamic albums

### ISSUE THREAD

**Issue by bic-ed** [zenphoto/zenphoto#1254]
I noticed it today for the first time. Links to dynamic album thumb pages created by the plugin in sitemaps are still in the form `root/virtual_folder.alb/`, while links to the same pages from the frontend are in the form `root/virtual_folder/`. This is not a really big issue, because links in the old form are still present and working in zenphoto, anyway it is non consistent with live links and this can possibly cause a lower ranking in search engines I guess.

**Comment by acrylian** [comment]
Thanks, good find. indeed not consistent and not good for Google (although if you have the canonical url option of the html_meta_tags plugin enabled that should have you covered for this). It indeed seems to use the `$name` instead of the (newer) `linkname`which is the same as on real albums but covers the suffix on dynamic ones. Probably a tiny change missed when the dynamic album change was introduced back then…

Btw, there is one occasion the suffix would be still be included which is when there is a real album folder with the same name.

**Comment by acrylian** [comment]
Yes, of course the sitemap should have the same URLs the front end uses. Was just an extra info in case not know and in case you had same named folders and dynamic album file.
