### ISSUE TITLE
Issue with i.php since 1.5.7.b support build update

### ISSUE THREAD

**Issue by davidarnoult** [zenphoto/zenphoto#1268]
Something is weird since latest update 1.5.7.b update. I have an error with i.php when my config
$conf['album_folder_class'] = 'external';

Image is not found, either the thumb with album views are all OK. I use printDefaultSizedImage() to generate my large image in image.php...

When $conf['album_folder_class'] = 'std';
I have this error instead:
NOTICE: Constant SERVERPATH already defined in /fullpath/zp-core/functions-basic.php(127) : eval()'d code on line 98

define called from eval (functions-basic.php(127) : eval()'d code [98])

from require_once (functions-basic.php [127])

from require_once (functions.php [18])

from include (index.php [14])

from index.php [56]

Is there anything wrong?

**Comment by davidarnoult** [comment]
With debug parameter with i.php request, I have:
Erreur Zenphoto : l’objet demandé n’a pas été trouvé.
Album : home/www/www.arnoult.com/albums/2000-2009/2003/Italie/Florence/2003-0005-0030.JPG
File is indeed correctly there with the right permissions...

**Comment by davidarnoult** [comment]
My $conf['album_folder'] = '/home/www/www.arnoult.com/albums/'; begins with "/", it is missing in the error message.

**Comment by acrylian** [comment]
If you have `$conf['album_folder_class']` having a define for `$conf['album_folder` needs to contain the name of the folder like `/albums/` (whatever you named the folder), NOT a path since it is the standard folder in the standard location. You only set a path if you use the `external` (like above webpath directory) or  `in_webpath` (like above the install but within webpath directory). This is documented right in the config file comments actually:

> // 'album_folder' is the name of the folder for the zenphoto albums.
// 'album_folder_class' determines how to interpret 'album_folder':
//    'std'         --	the folder must be a simple name. It resides in the root
//                      of the zenphoto installation.
//    'in_webpath'  --	the folder must be the full path of the album folder from
//                      the WEB root of the zenphoto installation. The WEB root of
//											your installation is the folder where your browser looks
//											if the link is just your domain (no folders).
//    'external'    --	the folder must be a full server path to the album folder.
//                      Images within an external folder are not visible to web
//                      browsers, so certain features such as flash players cannot
//                      display them

**Comment by davidarnoult** [comment]
I confirm you I have set up class:
$conf['album_folder'] = '/home/www/www.arnoult.com/albums/';
$conf['album_folder_class'] = 'external';

**Comment by acrylian** [comment]
So perhaps tell where your Zenphoto install is located actually.

**Comment by davidarnoult** [comment]
Thanks. It is a private gallery, How can I send you credentials by PM?

**Comment by acrylian** [comment]
I of course didn't mean you should expose a private site. I just need to know where in the path `'/home/www/…';` Zenphoto is installed relatively like '/home/www/www.arnoult.com/zenphoto/' or '/home/www/zenphoto/` or similar. Just anonymize the real paths. This will help to find out if the setting is right or wrong. We just tested this a while ago and all worked for us.

**Comment by davidarnoult** [comment]
Sorry. It is in /home/www/www.domain.com/htdocs/ on the same server. 
Albums are just at the same level in /home/www/www.domain.com/albums/

In apache access log, I have this for image.php request:
 - - [16/May/2020:20:05:22 +0000] "GET /1920-1949/1931/1931-0001-0001.JPG.htm HTTP/1.1" 200 6601 "http://domain.com/1920-1949/1931/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
 - - [16/May/2020:20:05:22 +0000] "GET /zp-core/i.php?a=1920-1949/1931&i=1931-0001-0001.JPG&cw=0&ch=0&q=85&wmk=%21&check=84d99b1e570cb3ef4a2dad39c896f863f14e78c1 HTTP/1.1" 302 284 "http://domain.com/1920-1949/1931/1931-0001-0001.JPG.htm" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
 - - [16/May/2020:20:05:22 +0000] "GET /home/www/www.domain.com/albums/1920-1949/1931/1931-0001-0001.JPG HTTP/1.1" 404 777 "http://domain.com/1920-1949/1931/1931-0001-0001.JPG.htm" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
It confirms 404 error for i.php. Looks like it would be a permission issue / apache problem?

**Comment by acrylian** [comment]
Despite the folder name the actual we broot of the domain `www.domain.com` is `/home/www/www.domain.com/htdocs/`, correct? I assume you have checked that `/home/www/www.domain.com/htdocs/ is really the full server path (by echoing the SERVERPATH constant for example)? Just asking to be sure as sometimes above home or similar there is a server name or something.

And yes, permission issues could cause all sorts of "funny" issues. Although that likely would be not a "not found" but a "forbidden" error. Which makes me think the path might not be right.

**Comment by davidarnoult** [comment]
It was a permission issue, not path. I have reset owner and permissions of albums files including zenphoto script files and it is now back to normal. Thanks for helping anyway!

**Comment by acrylian** [comment]
Great! Glad it was that "simple"!
