### ISSUE TITLE
Fluid video element in album view.

### ISSUE THREAD

**Issue by RolandTi** [zenphoto/zenphoto#1288]
Hello, in album view, the `<video>` tag include height and width.
But maybe Zenphoto should let it empty.

As explained in this article : https://css-tricks.com/fluid-width-video/ it's easier to make responsive template by using css sizing.

What do you think ?

Thanks !

**Comment by acrylian** [comment]
Not really. We use the size the video actually has (if it can be read) to display the default. Otherwise it may be displayed larger than it actually is and you can always switch to full screen. The same article suggests you can and should do this via CSS, in our case the theme.You even need JS to properly resizes a video on browser width changes.

**Comment by acrylian** [comment]
However as I think about it, we probably an do this for the default video. Videoplayer plugins of course may do their own thing, so the theme should in any case have the required CSS.
