### ISSUE TITLE
Turning on Obscure cache filenames does not rename existing cache files, but recreates them all

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1295]
Turning on Obscure cache filenames under Options-Security does not rename existing cache files, but recreates them as needed. Requiring the entire site to be re-cached, which can take days on a shared hosting plan, if it works at all. If the images were previously cached, it causes duplicate files, and then it does not achieve its goal of- “Cause the filename of cached items to be obscured. This makes it difficult for someone to “guess” the name in a URL.”, since the original cache images are still there.

Ideally this option would check to see if the cache images already exist and rename them rather than recreate them, thus solving the previously mentioned issues.

This was tested in 1.5.7 and 1.5.8RC.

**Comment by JesseHC** [comment]
Doing this would also allow the user to create the cache images locally, much faster, with the Obscure cache filenames turned off, transfer them to their live server, run cacheManager to see that everything is cached, and then turn on the option if they wanted.

I’m personally dealing with the issue of my site being super slow when first launching on the live server because everything needs to be cached. I’ve tried to get cacheManager to work for days, and it takes hours before it will eventually fail. This is with the “Protect image cache” and “Secure image processor” under Options-Image turned off.

I know about the image size limitations, and I’m not sure that is the issue. I think it has to do with the large amount of files, and what looks like eventual timeouts from the MySQL server-

```
{661435:Sun, 04 Apr 2021 08:21:29 GMT}
  USER ERROR: MySQLi Error: ( DELETE FROM `[prefix]plugin_storage` WHERE `type`="ipBlocker" AND `aux` < "[number]" ) failed. MySQLi returned the error MySQL server has gone away in /host/zenphoto/zp-core/functions-db-MySQLi.php on line 95
  trigger_error called from query (functions-db-MySQLi.php [95])
    from ipBlocker::adminGate (ipBlocker.php [316])
      from zp_apply_filter (functions-filter.php [150])
        from admin_securityChecks (admin-functions.php [4316])
          from admin-edit.php [14]
{659377:Sun, 04 Apr 2021 08:21:29 GMT}
  USER ERROR: MySQLi Error: ( DELETE FROM `[prefix]plugin_storage` WHERE `type`="ipBlocker" AND `aux` < "[number]" ) failed. MySQLi returned the error MySQL server has gone away in /host/zenphoto/zp-core/functions-db-MySQLi.php on line 95
  trigger_error called from query (functions-db-MySQLi.php [95])
    from ipBlocker::adminGate (ipBlocker.php [316])
      from zp_apply_filter (functions-filter.php [150])
        from admin_securityChecks (admin-functions.php [4316])
          from cacheDBImages.php [13]

…

{736005:Tue, 06 Apr 2021 11:09:10 GMT}
  USER ERROR: MySQLi Error: ( DELETE FROM `[prefix]plugin_storage` WHERE `type`="ipBlocker" AND `aux` < "[number]" ) failed. MySQLi returned the error MySQL server has gone away in /host/zenphoto/zp-core/functions-db-MySQLi.php on line 95
  trigger_error called from query (functions-db-MySQLi.php [95])
    from ipBlocker::adminGate (ipBlocker.php [316])
      from zp_apply_filter (functions-filter.php [150])
        from admin_securityChecks (admin-functions.php [4316])
          from admin-edit.php [14]
{768142:Tue, 06 Apr 2021 11:35:47 GMT}
  ERROR: cURL request failed: Empty reply from server
```

On my local test server, creating the entire cache only takes about an hour.

**Comment by acrylian** [comment]
A live server is not under the same condition as a local server as that of course has not other overhead like actual visitors. It is normal that things work a lot faster locally than on a actual liver server.

As you say you know about the image size limitation: Caching or more specific processing images is the most heavy task. It depends also which mode of the cachemanager you use and if it. On some the curl way works better (mine) and on some the legacy way does which actually is less reliable. But on large sites this even takes a lot hours locally (Tested with ten thousand+ images).

I am not sure if checking for cached files and then renaming them will be really faster. I mean it's file system operations which also may cause some overhead. 

Regarding the duplicate cache files, you should normally clear the image cache when changing things related to it. 

I personally think that the old obscure cache filename option is not providing that much benefits. The image is loaded in any way by the visitor and referenced as it would with its "real name" and also static. The actual threat would not be a normal visitor but image scrapers that try to download something, And all they need to do is to go through all pages like a Google bot would do.  This is not really "securing" much.  It even is not that good for SEO since the cache image names loose any speaking meaning. I ​personally never use or used it. I even thought of removing this option in the future. 

I will take a look if such a check could be done without much work but I am actually not sure I want to invest much time here.

**Comment by acrylian** [comment]
Can you try that with the ipBlocker disabled, too? It looks as if that may infere with the cURL request. Have you set IP anonymisation active and which setting? Full anonymisiation basically turns it off so any check will fail always.

**Comment by JesseHC** [comment]
I have been trying both methods, Classic and cURL, to see if it made a difference, but was mostly sticking with cURL.

ipBlocker wasn’t blocking any IPs, but it was turned on to try to discourage password probing. I’ve turned it off.

I’m not based in the EU, so I currently do not have Anonymize IP turned on.

After reading your reply, I’ll probably just try turning off obscure cache filenames, create the cache locally, and copy it over.

I wish there was a cron job that could be set to off hours to run in place of cacheManager, to check and create cache images. I know someone created one in the past, but when I tried it back then, it did not work for me.

**Comment by acrylian** [comment]
cURL should be the better and more reliable way if it works on the site. For unknown reasons to me it does not on some servers.

The actual images you want to "secure" are the full size images normally and that is best done using an external albums folder and/or renaming that. However whatever a browser can load and display can be copied and if it is the browser cache.

> I wish there was a cron job that could be set to off hours to run in place of cacheManager, to check and create cache images. I know someone created one in the past, but when I tried it back then, it did not work for me.

"Normally" we consider pre-caching not "necessary" since it is done on the fly. But I certainly understand that it might be on some sites.

A cron would have to either go through all pages like a bot to trigger caching on the fly or like the sitemap plugin go through all contents.
