### ISSUE TITLE
Suggestion: Validate custom album image sorting

### ISSUE THREAD

**Issue by SubJunk** [zenphoto/zenphoto#1311]
I recently had a user save an invalid custom image sort for their album which broke their pages. Can be reproduced by entering any value in there that does not correspond to a column

![image](https://user-images.githubusercontent.com/584228/150651927-1ce82ea6-9759-4f57-97ed-e67865d0c6e5.png)

**Comment by acrylian** [comment]
That's a bit complicated I fear, because technically you also use combinations. Best most bullet proof would be to just offer all custom fields in the selector…

**Comment by acrylian** [comment]
Since this refers to the actual db columns most users will have no knowledge about, we probably should  indeed just offer all columns that make some sense for sorting to make this as simple as possible. 

We could keep the custom option with a note that this requires more knowledge … Or we remove it and leave more complex sort orders to coding only.

**Comment by SubJunk** [comment]
I agree. I don't know about all use-cases but for my websites, my "admins" are more like "users" so I don't want them to have those kinds of abilities. I would be happy for it to be disabled. I have just removed that part of the code on my server to prevent it happening again.

**Comment by acrylian** [comment]
I even never used this option myself and almost all site owners I did Zenphoto site for are also "users" only with no slightl idea what a database is at all. Not everything needs to be possible via the backend IMHO.

**Comment by acrylian** [comment]
Btw, it is always indeed a good idea to close the site when performing an update using the included site_upgrade plugin.
