### ISSUE TITLE
tag_suggest plugin and <datalist>

### ISSUE THREAD

**Issue by RolandTi** [zenphoto/zenphoto#1340]
Hello !
The tag_suggest plugin could be now much lighter by using the <datalist> element instead of javascript ?

Have a nice day !

**Comment by acrylian** [comment]
Not sure what you mean by "element". You need JS to filter in any case, so it really does not matter for the current setup. But regardless the plugin has aged a bit and will be reworked at sometime in the future to not load all tags anyway (but not for 1.6 as it requires some other central changes).

**Comment by acrylian** [comment]
Edit: Sorry, read to quickly and misread the element. But my statement above still applies.

**Comment by RolandTi** [comment]
Hello, 
as I saw datalist at MDN https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist 
it's works like the tag_suggest plugin frontend.
But yes, you still need a plugin to control the tags you want to show or not :)

**Comment by acrylian** [comment]
Yes, it does but it has no performance benefit if still all tags are loaded. It is good Better is to get the tags matching the search query and then you don't need datalist. Datalist is good directly if you have only a few items to filter but not on large sites hundreds of tags or even more possibly. But as said that is more work we don't do right now because it is connected to some plans for the future.
