### ISSUE TITLE
Login fails after upgrade

### ISSUE THREAD

**Issue by kochs-online** [zenphoto/zenphoto#1344]
I recently upgraded from version 1.5.4 to version 1.5.9 and subsequently to current Master (version 1.6RC). After the upgrade everything was fine (using the same browser session and thus the same session cookies), but today neither me nor my users can login despite using the correct passwords for the accounts.

I compared the entries of the `adminstrators` table with my SQL backup from before the update and no difference was found.

Is there some kind of salt used in hashing the passwords that might have changed?

**Comment by kochs-online** [comment]
Might this be related/connected to #1247?

**Comment by acrylian** [comment]
No idea. We encountered this recently as well once but were not able to reproduce it..  

> Is there some kind of salt used in hashing the passwords that might have changed?

No, we had the plan to finally switch to native PHP password handling originally. Lacking time to test that and the importance to get PHP 8 comp out we pushed that for later.

> Is there some kind of salt used in hashing the passwords that might have changed?

We didn't change anything. A general hash is within the option 'extra_auth_hash_text' (populates the constant HASH_SEED) and then used in combination with user name and pw to generate the pw hash. That is stored within the db.  That option is set via setup/set-option-defaults.php and has not been changed since forever…

**Comment by acrylian** [comment]
Hopefully your users have either challenge-response-questions set and/or valid mail addresses so they can reset their passwords. Otherwise there is no way except to delete/clear the whole administrator table…

But of course the option issue may be related so perhaps look at that. Also clear all cookies.

**Comment by acrylian** [comment]
To that option above there would only be changes if the libauth version  would have change, so if we added new right level or similar. But we didn't. But there are other options like password strenght etc that may be related. So if the missing index  from #1342 messed up options that may be related to that. I would not have recommended to install it on a production site yet actually (even if we call it RC already…)

**Comment by kochs-online** [comment]
> A general hash is within the option '`extra_auth_hash_text`' (populates the constant `HASH_SEED`) and then used in combination with user name and pw to generate the pw hash. That is stored within the db.

> So if the missing index from #1342 messed up options that may be related to that.

That's it! Currently there are two entries for `extra_auth_hash_text` in the `options` table. After changing the `name` value for one of the entries logins are working again.

So it seems duplicate entries were created in the past and the index that existed until the last update made the database return the entry with the lower `id`. After deleting the index the entry with the higher `id` was returned and the password hashes didn't match any longer.

**Comment by kochs-online** [comment]
I just checked my backup from version 1.5.4 and there is only one entry for `extra_auth_hash_text`. So the new entry must have been created while upgrading, most likely after I had to drop the index `unique_option` on table `options` to make the `utf8mb4` conversion work.

**Comment by kochs-online** [comment]
Closing this issue as the root cause has been found and fixed.
No code change required.
