### ISSUE TITLE
Image metadata fields Time Created and Digital Creation Time are being set to date when image page loads instead of actual time from image metadata

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1359]
In Image options, under Metadata, have the fields _Time Created_ and _Digital Creation Time_ set to display. Open any image page with an image that contains this metadata. Instead of showing the time from the file, both fields will show today’s date.

For example, looking at my test image metadata it has the following IPTC properties:
> Date Created: 2016:04:03
> Time Created: 00:31:43
> Digital Creation Date: 2016:04:03
> Digital Creation Time: 00:31:43

Clicking on Image Info on the image page in Zenphoto you will see this:
![Zenphoto 1 6 Image Info with wrong Time Created and Digital Creation Time](https://user-images.githubusercontent.com/82089671/208114270-ddf453c6-ac85-4d80-af45-29a0d89760fe.png)

Notice both fields show the day's date when I tried to load the page instead of the time from the metadata. At first I thought it might be pulling it from the cached image created, but it seems to always show the day's date, even if a cached image already exists.

I know they come from function.php:
`'IPTCTimeCreated' => array('IPTC', 'TimeCreated', gettext('Time Created'), false, 11, true, 'time'),`

`'IPTCDigitizeTime' => array('IPTC', 'DigitizeTime', gettext('Digital Creation Time'), false, 11, true, 'time'),`

This is happening in Zenphoto 1.6, and the news post for 1.6 says you changed how date formats are processed, so maybe it has something to do with that?

A minor issue, but you can also see from the screen shot that the fields _Original Time Taken_ and _Time Digitized_ are only showing the dates, and not the time, or at least not the full date and time as it is in the metadata.

EXIF properties:
Date/Time Original: 2016:04:03 00:31:43
Create Date: 2016:04:03 00:31:43

What function.php is calling:
```
'EXIFDateTimeOriginal' => array('SubIFD', 'DateTimeOriginal', gettext('Original Time Taken'), true, 52, true, 'time'),
'EXIFDateTimeDigitized' => array('SubIFD', 'DateTimeDigitized', gettext('Time Digitized'), true, 52, true, 'time'),
```

I know you can always disable the fields and ignore it, but I wanted you to be aware of the issue.

**Comment by acrylian** [comment]
Thanks, I see what you mean. The dates seem okay but the times for some reason are processed as dates, too. After all the exif dates also have the `:` instead of the `-` so it "looks" the same. The code examples you cited are the definitons of the fields, the display and formatting is happening in other places. We'll try to look into that.

Can you please additionally tell if your server has the intl PHP extension? We basically have two internal formattings based on if it is or not.

**Comment by JesseHC** [comment]
Both my local test server and my live server have the intl PHP extension enabled.

My local test version of MAMP has it with this info:
> intl
> Internationalization support	enabled
> ICU version	56.1
> ICU Data version	56.1
> ICU TZData version	2015f
> ICU Unicode version	8.0

My live server has this:
> intl
> Internationalization support	enabled
> ICU version	69.1
> ICU Data version	69.1
> ICU TZData version	2021a
> ICU Unicode version	13.0

**Comment by acrylian** [comment]
Thanks, I'll try to look into that over the weekend.

**Comment by acrylian** [comment]
We have made some changes to date handling. Localized dates must be enabled now via the options. Please try if this fixes this perhaps as well.

**Comment by JesseHC** [comment]
It did not fix the issue for me.

This was tested locally in MAMP running PHP 7.4.12, 7.4.33, and 8.2.0.

Time Created and Digital Creation Time in Image info is still messed up and shows the date Zenphoto was installed and/or the page was loaded and the cached image created.

For Date Created and Digital Creation Date, the date is right, but it throws in a default time instead of the correct time (if set to also show a time in Date format under Options-General).

> Original Time Taken:	April 03, 2016 12:31 AM
> Time Digitized:	April 03, 2016 12:31 AM
> Date Created:	April 03, 2016 12:00 AM
> Time Created:	March 17, 2023 12:31 AM
> Digital Creation Date:	April 03, 2016 12:00 AM
> Digital Creation Time:	March 17, 2023 12:31 AM

Setting it to localized date-
> Original Time Taken:	April 03, 2016 7:31 AM
> Time Digitized:	April 03, 2016 7:31 AM
> Date Created:	April 03, 2016 7:00 AM
> Time Created:	March 17, 2023 7:31 AM
> Digital Creation Date:	April 03, 2016 7:00 AM
> Digital Creation Time:	March 17, 2023 7:31 AM

In the Metadata for the image on the image tab for the album-
> Original Time Taken: 	2016:04:03 00:31:43
> Time Digitized: 	2016:04:03 00:31:43
> Date Created: 	20160403
> Time Created: 	003143
> Digital Creation Date: 	20160403
> Digital Creation Time: 	003143

Refreshing the metadata for the image does nothing.


Here’s the official reference image for IPTC Photo Metadata Standard 2022.1 if you want to have an image to test-
https://iptc.org/std/photometadata/examples/IPTC-PhotometadataRef-Std2022.1.jpg

From the [IPTC Photo Metadata Standard page](https://www.iptc.org/standards/photo-metadata/iptc-standard/).

Image Metadata info from Images tab (you can see it doesn’t have all the date and time fields that an image taken with a digital camera might have, but it still will demonstrate some of the issues):

> Original Time Taken: 	2022:10:19 22:01:00
> Date Created: 	20221019
> Time Created: 	220100+0000

In Image Info, you can see the Date Created has the wrong time and the Time Created has the wrong date.

> Original Time Taken:	October 20, 2022 5:01 AM
> Date Created:	October 19, 2022 7:00 AM
> Time Created:	March 17, 2023 10:01 PM

**Comment by acrylian** [comment]
We just noticed that we haven't updated some dateformat usages properly so that might be related. Let's test again once we updated that.  

Thanks for the example image link. That's useful in any case.

**Comment by acrylian** [comment]
We made some more changes. I did test the test image. This is the image meta with localized dates:
![imagemeta localized](https://user-images.githubusercontent.com/2474309/226123187-f1953f3a-cad5-4cb3-ac97-6994ffd522e7.jpg)

And this without (German dateformat a la 1.2.2023 working correctly)
![imagemeta no localized](https://user-images.githubusercontent.com/2474309/226123190-db7ed2ec-e6ac-4c0b-92a7-3612bd7a2b6a.jpg)

That "Time Created" is of March 2023 is not a read error but that is the file time - mtime - we apparently using here for theme display and not the meta value. That is correctly read and displayed on the backend:

![imagemeta backend](https://user-images.githubusercontent.com/2474309/226123267-d68b6ee5-496d-4e07-936f-24976404fa62.jpg)

So the mystery is why we are using the mtime instead of the meta value. No idea but this is probably that way for ages as we didn't change metadata stuff since forever.

**Comment by acrylian** [comment]
I have take a look. This is the metadata date processing for an image within the image class:

![Bildschirmfoto 2023-03-23 um 11 47 02](https://user-images.githubusercontent.com/2474309/227180903-c76576c3-e84b-4a86-8d13-908bfae49cd3.jpg)

There the date is set for the standard image date. For some reason -  I guess forgotten legacy stuff - there is a $xdate var set for image date fallback with then the mtime. 
![Bildschirmfoto 2023-03-23 um 11 51 18](https://user-images.githubusercontent.com/2474309/227181273-c182343e-905a-47a4-8777-c030bc9d63f4.jpg)

But I didn't find any mtime uses for the metadata. So I still need an image where this happens. Otherwise I will need to close this a "works for me"

**Comment by JesseHC** [comment]
Most of the issues with blank dates in Zenphoto are coming from images or videos that don’t necessarily have date and time info in EXIF, IPTC, or XMP metadata fields, but like any file, they do have Creation date and a Modification date set in the file properties. So if the date and time cannot be pulled from extra metadata, Zenphoto should at least be using the Creation date instead of leaving blank dates.

Since I’ve seen other people having this issue on the forum, and don’t want to make it seem like it is my images only having the issue, I’ve linked to sample images online that will show you what I mean.

They will all display blank dates in the Images tab, and will then default to the 1969 description date in the RSS feeds.

**GIFs**
Here’s an example image from the [Wikipedia entry](https://en.wikipedia.org/wiki/GIF)-

https://en.wikipedia.org/wiki/GIF#/media/File:Sunflower_as_gif_websafe.gif

**Animated GIFs**
Same goes for animated GIFs.

https://en.wikipedia.org/wiki/GIF#/media/File:Newtons_cradle_animation_book_2.gif

**PNG**
From the [Wiki entry](https://en.wikipedia.org/wiki/PNG).

https://en.wikipedia.org/wiki/PNG#/media/File:PNG_transparency_demonstration_1.png

**JPEG**
A JPEG from a digital camera exported in Photoshop Save for Web with metadata turned off (there are a few options for this), and many other image editors will do this. I've attached a personal image for you to check out.
![PS_Save_for_Web](https://user-images.githubusercontent.com/82089671/227466451-66c01df5-c00e-4ec4-89f4-9c78bddd8e49.jpg)


**Screenshots**
From the [Wiki](https://en.wikipedia.org/wiki/Screenshot).

This one also has Modify Date, Datecreate, and Datemodify in the PNG properties, but shows nothing extra.
https://en.wikipedia.org/wiki/Screenshot#/media/File:QEMU_6.2_screenshot_(cropped).png

**Scanned images**
From [here](https://www.scanmyphotos.com/samplescans.html).

Even this example has Modify Date in EXIF properties and Modify Date and Metadata Date in XMP properties and doesn’t work.
https://www.scanmyphotos.com/images/samplescans/300DpiSample.jpg

**MP4 video files**
From [here](https://samplelib.com/sample-mp4.html).

https://download.samplelib.com/mp4/sample-5s.mp4


All images have a blank date.
![All have blank Dates](https://user-images.githubusercontent.com/82089671/227466320-f27af24c-ff05-43d9-9750-ec389e79b5be.png)

**Comment by acrylian** [comment]
Close for now, for future consolidate possible "date issues" in one ticket (see last comment on #1363)
