### ISSUE TITLE
Upload form template

### ISSUE THREAD

**Issue by yohan9999** [zenphoto/zenphoto#1368]
Hi,

Just updated my Zenphoto Galery from version 1.5.9 to 1.6 and noticed something weird. The jquery upload form was well designed with previous version :

![zp1](https://user-images.githubusercontent.com/85416692/209239577-183c1305-fcc7-4feb-befe-856cf7ba6e17.png)

And now looks like an old 90's Internet website :

![zp2](https://user-images.githubusercontent.com/85416692/209239861-f9b7ed94-2daa-450b-9b48-96ab894e4628.png)

I didn't get any errors during the update process. I'm using Apache PHP 7.4. Is there something wrong with the update, a missing file, or it's just like that now ?

**Comment by acrylian** [comment]
Sadly it is like that for now. When we updated the 3rd party script we had some trouble to get it working properly at all so the styles where a casualty. They were actually from the script itself using jquery ui which we actually still use but we didn't get that back proplerly

Since we had lots of "more important" stuff to do we choose to just keep it that way being glad it worked at all. Also just in November the script has been abandoned by its developer so we most likely will have to look for a replacement sooner or later anyway.
