### ISSUE TITLE
cachemanager.php Enhancement suggestion

### ISSUE THREAD

**Issue by FilippoBoscarino** [zenphoto/zenphoto#1376]
Having a ZenPhoto Site with more than 26k pics (most photograpic HD quality) and multimedia files, the cache creation process is particularly felt by my side...
I am planning to move my server to a new more powerful instance, but within this moment I have to fight with the optimization of resources and efficiency in the code, without forget data integrity.

I have always used GDLibray to generate thumbs, with Classical method, but it is really a mess:
1) 'cause in albums that can have also 500 pics, you can have to rerun the cache creation process tens of times,
2) 'cause it is not controlled the success of operation
3) somethimes, also if the server is relaxed, some reload of the process do create not even a thumb (I investigated but did not really understand why)
4) last but not least, because when produced, some cache pics can be created not integrally (just half pic and the rest grey or white)

I decided, starting on version 1.6, to migrate to Imagick Libs with cUrl method (much more trustable) and I started to swim in the muds of issues ;)

First of all, in my environment it is impossible to use on Albums that are larger of 40-50 pics, otherwise the "504 Gateway Time-out" is the only concrete and prosaic answer to my heart-beated suspance every time...
I also tried the solution to finger click a  reload and reload again, but this can not be consider a solution.

I am trying to develope a solution to this issue by myself, modifying the code, and I will be glad to share my results if I can have some.
I do not want to fork out something that can compromise the ability to follow the natural updating of your CMS, so I am thinking to something tha can be modular (a plugin or something that could be switched on/off on demand).

Anyway a good compromise should be to implement a segmented and auto-reloaded version of the procedure, in thesimilar way already engineered for metadata reload and db refresh.

I would be very glad if you consider this suggestion and eventually cooperate to reach a solution.

**Comment by acrylian** [comment]
The classic way of the cache manager never worked reliable for me which is why we/I introduce the cURL method. For some reason it does work not properly on some servers while it works perfectly on others. But glad to see it works better for you, too.

> in the similar way already engineered for metadata reload and db refresh.

That is basically not that different just divided into several pages and not using cURL. On very large sites that also may have problems.

In any case the image processing is of course a huge demanding task for the server with Zenphoto. Especially if you have lots of images and even large ones dimension wise. So on really large sites you may have to work yourself through to albums one by one. Good is that once cached it's permanent unless you clear it yourself.

As you surely know pre-caching is technically not exactly necessary since Zenphoto will always generate images requested and missing when needed. Only the first visitor will get that processing delay: https://www.zenphoto.org/news/caching/ 

We may add pre-caching of registered sizes on upload in the future. We really don't want to do any major changes to 1.6 respectively 1.x release though anymore (please see the 1.6. release post again). 

But we of course welcome any third party effort for example via a plugin just like the cacheManager itself. So you could use that plugin as a start. Whatever you try to do you will need to use the core image processor in any case.

**Comment by acrylian** [comment]
> in the similar way already engineered for metadata reload and db refresh

Just to add: Probably just dividing the whole process in several "album pages"  like that would be a pragmatic way. the meta refresh etc uses some rather complicated meta refresh construct for that. Probably better way would be to use a JS reload after each chunk to achieve the same. That said I'll gladly co-operate on this.

**Comment by FilippoBoscarino** [comment]
> Only the first visitor will get that processing delay
Unfortunately this not applies to my environment. If not precached, user receive at list a 50% of broken images for each page.

> We may add pre-caching of registered sizes on upload in the future.
Seems a good solution but what about ftp loaded images? Are them included?

> We really don't want to do any major changes to 1.6 respectively 1.x release though anymore (please see the 1.6. release post again).
Clear to me, but I have to address a solution for meanwhile.
Let's stay tuned...

**Comment by acrylian** [comment]
> Unfortunately this not applies to my environment. If not precached, user receive at list a 50% of broken images for each page.

Perhaps your environment is not really sufficient for the size/type of site you are using? If your server generally easily gets to the "limit" so to speak it always will. Something really can't be solve by code but by infra structure upgrades. Another way is to not use huge "fine data" images. The smaller (not filesize!) the less work for the server (we have an article for that as well). Just asking.

> Seems a good solution but what about ftp loaded images? Are them included?

No, they cannot. Direct file system operation are outside of ZP's control. ZP is file system based but only gets to know these when on discovery (as documented on the caching article above).

**Comment by FilippoBoscarino** [comment]
Hi, I finally developed a ZenPhoto plugin that can mitigate this issue, named smartCache v.1.0.0.
It is dependant on cacheManager zp_extention (1.6.x version) and it need this extention active to work fine.
It offers two new buttons, one in Admin Dashboard page, the other in the Album Edit page.
They are are both labelled "Smart Cache manager" and they offer a much flexible way to generate caching sizes.

Basicly it is already possible to:
- break the process of generating chache sizes in paged chunks with defined number of items every chunk.
- enable an auto-advance process to easily provide batch operations
- plugin options are: number of items per chunk, enable/disable auto-advance and its waiting time, php set timeout for processes
- auto-advance process can be paused and restarted to easily verify things; a chunk can be reloaded as well
- number of items per chunk, as well as auto-advance method and timing, can be defined as plugin option, but also on the fly, directly in the process launch
- all the images (already cached and new ones) are thumbed in page, for a better control of the whole process
- thumbs showed are a bit bigger (50px high) to give users the ability to better see the single cache size results
- passing mouse pointer on not loaded images, attempts reloading of cache size

In my purposes there are also a couple of other improvements like:
- a button to delete wrong items cache sizes, and reattempt the creation on the fly
- other little nice-to-have and process debug improvement

So I would be very glad to share it and assure that can be future-proof, towards 2.x versions of ZenPhoto.
I want to publish it very soon on my website (as soon as I will win over troubles earned with the 1.6 migration ;) ).
But in meanwhile, can you please suggest me where is the best place where to publish in your universe, to begin to spread it and eventually get feedback/bugs/suggestions from user.
I don't know if https://forum.zenphoto.org/ is the best place to start.
Cheers

**Comment by JesseHC** [comment]
I was typing up my reply and about to hit Comment when I saw your post. Thank you for trying to address this issue!

For me, the biggest pain point in using Zenphoto is constantly dealing with the cache. On any larger site with a few thousand images, or even a small folder with a dozen large images, making any changes to the template or image options can cause a site on a shared hosting plan to lockup or not work.

Telling the users, or even expecting them, to use small images in a world where phones now (Android and iPhone) take 48-megapixels pictures is not realistic. Or at best, a way to make sure no one ends up using Zenphoto. If the answer is telling them to pay for a dedicated server, most replies would probably be it’s easier and cheaper to just pay for Flickr or any other image hosting plan.

Even when cachemanager does work on smaller images, making changes to a site, and then expecting the site users to have to deal with each image slowing loading on a page is a great way to make sure no one ever uses your site or comes back.

What I would LOVE to see is an offsite/offline mode for cachemanager. This would work exactly as it does now, but would not create symlinks for larger images. This way more advanced users, or people having problems creating the cache on their hosting plan, could run Zenphoto on a local version (MAMP/WAMP) with much more resources and then upload the cache folder to get around it not working or being slow to work.

Right now if you try to do that an FTP program will instead break all the links for the larger files and upload them instead, which can cause your site to more than double in size.

Another option I would like to see added to cachemanager is the ability for Zenphoto to automatically run it, or at a set time, as a cron job to catch files that might have been missed when uploading them by FTP or for users not familiar with cachemanager. That way, the hassle wouldn’t be put on viewers to the site to slowly generate all the cache images.

There used to be an extension called zenphoto-precache that tried to address some of these issues, but frankly, I could never get it to work right.

https://www.zenphoto.org/news/zenphoto-precache/

**Comment by FilippoBoscarino** [comment]
Hi JesseHC, thanks for your reply.
I would keep your suggestion for maybe new versions of my plugin, but IMHO one of the biggest issue at the moment is that both libraries GDlibrary and Imagick are not completely trustable in their process success result (at least in ZP implementation, I have not experience on the specific libraries themselves).
As in my experience, using GDlibrary on large images on limited resources can carry on some faults results as images with an half completely grey.
With Imagick sometimes happens that file are produced but they are corrupted and not readable.
So a human process to control results is mandatory to have a pro result on your site.
I normally use my plugin in the auto-advance mode on one entire folder or branch of the site, with 15-20 pics/chunk and let it work alone. At the end of the process I reload the same process with 0 items/chunk (that means all the items) and verify by eye the result.
This is **for now** a good semi-automatic solution, but I am very interested in finding out more robust and  reliable ones.

I have planned to drill down the whole caching procedure, but not done yet.

In any case I do not think that the ftp approach would be the best.
I have more than 26k pics and media on my site and it going to grow everyday.
I think that the moving so many files, also if in an incremental way, should be a mess and a problem in band usage for the server.
Something managed by crontab should be nearer to the hopeful solution.

Last opinion about precache extension. I do not think could not be either the solution: on heavy photos could affect page rendering time, and this could be a disadvantage very important toward user stickyness.

**Comment by acrylian** [comment]
@FilippoBoscarino 

>I don't know if https://forum.zenphoto.org/ is the best place to start. 

Thanks for your work. I would love to take a look. Best you create a Github repo for it. The issue about processing is not GD and IMagick it is just that image processing is a huge extensive task to.

> Porting to PHP v.8.x, has also introduced a new issue on correct image orientation, so it is really difficult at this moment consider a full-automated process really reliable.

To note that image orientation processing has been reworked in 1.6.1a as it was rather broken and even incomplete regarding mirroring. Even if 1.6.1a is work in progress you should primarily test your plugin with that.

@jesseHC

The offline solution is to use caching on your local ist. Regarding the symlinks: Those had been added so you don't cache image sizes that already have the right size (or are too small to be resized) to avoid space issues. You can easily have that with lots of images. We surely can add an option to disable symlinks.

As mentioned we think about pre-generattion registered sizes on upload. although that may slow down upload of course. Perhaps for speed's sake we need to rethink the on the fly image size creation and only allow predefined registered sizes.  However that then would mean that on any change pre-caching would be required.

**Comment by acrylian** [comment]
May I suggest the name smartImageCache because we have other caches like the html cache and the rss cache which for history reasons teh cacheMAnager provides some tools for (we plan to divided that properly sometime in the future so the cacheManager is images only).

**Comment by acrylian** [comment]
> I will follow your versioning. Have you an idea about when releasing?

Sorry no, I work on ZP stuff as time allow and whatever I say I will probably not be able to keep it ;-)

> but it always leave out ftp uploading (I use it so much....)

Well, since FTP is bypassing ZP the only way is to run pre-caching in some way if the on the fly generation is not the best for your site's size. I basicllay like the on the fly way for that reason and are annoyed on some other well know CMS that works with only predefined sizes so you have to re-generate everything on every tiny change…

**Comment by acrylian** [comment]
> I will publish it on GitHub soon and propose link here

Great, we later gladly add an entry to your extension section. If it is a huge improvement hopefully there is the chance to later join it into core. But that's not for 1.x anymore of course.

**Comment by acrylian** [comment]
Great, thanks. One small thing beforehand: It's "Zenphoto" and not "ZenPhoto". We even have an article about that https://www.zenphoto.org/news/how-to-write-the-application-name/ ;-)

**Comment by FilippoBoscarino** [comment]
Sorry... I'll change it

**Comment by acrylian** [comment]
Github generally handles basic redirections it seems.

Two very small cosmetic suggestions I don't want to open tickets for since it is of course your plugin and code:

- In ZP we generally use camelCase function/method names (we have underscore ones which are legacy names that eventually will be aligned some time).
- We use phpdocumentor docblocks for comments (of course its the first version and documenting is a pain ;-))

This will just save some time alter in case we should decide to take this officially in at some time.

Will try to test the plugin soon!!!

**Comment by acrylian** [comment]
Since you use classes you only need to make sure the class name is unique then all methods cannot have naming conflicts.

Regarding docblocks take a look here:
https://docs.phpdoc.org/3.0/guide/getting-started/what-is-a-docblock.html#what-is-a-docblock

If you use any IDE or other edite like we do (we use Netbeans) it may be able generate these easily. But all cosmetic lets first test of course.

**Comment by FilippoBoscarino** [comment]
> Since you use classes you only need to make sure the class name is unique then all methods cannot have naming conflicts.

This plugin is a part of a bigger development where I generated other libs (and subsequent functions) to support Templates development and some custom made Themes as well.
Unfortunately many plugins and extensions are engineered with a model of "printThisPluginDeliverable()" functions, which directly echo the result to screen, not with a "getThisPluginDeliverable()" that can pass the results to a string, that can be echoed later or after some controls.
So the prefix on functions name was an easy way to avoid overlapping.
But as said before: no problem to align somehow, for future compatibility.

> If you use any IDE

I am an artisan of editor :)
But no problem, I will address the points asap

**Comment by acrylian** [comment]
> This plugin is a part of a bigger development where I generated other libs (and subsequent functions) to support Templates development and some custom made Themes as well.

Sounds interesting. Feel free to contact me directly via mail if you like to  talk about something. 

> Unfortunately many plugins and extensions are engineered with a model of "printThisPluginDeliverable()" functions, 

Generally we have get and print versions. But of course if it is a theme function that should output things there may not be a get version if it it not needed.  I was referring to method names like `work_albums_tree()`.

**Comment by FilippoBoscarino** [comment]
> Sounds interesting. Feel free to contact me directly via mail if you like to talk about something.

I had the stupid goal to address the 1.6 migration, the production of a new Template and the upgrade of the libraries, all at the same times and now I am in a real mess.
But I certainly do it as soon as I go back to the surface.
I like very much your platform and it would be great to exchange some chat

> work_albums_tree()

I see. Item received

**Comment by JesseHC** [comment]
Thanks for the update! I noticed some small issues.

If running it in chunks, if an image fails, there is no way to see what image it is because the page refreshes on each new set of chunks.

Confused why it is not caching multimedia objects, when they can have sidecar images that often need to be cached?

This might be an issue with cacheManager, but your extension is highlighting it.

On mine:
_Multimedia: 1071 sizes not required_

And on the specific items: _“Multimedia object. No cache needed”_

When, in fact, almost all of them had sidecar images that needed to be cached.

Maybe shrink the plugin icon to match the other icons at 16x16.


**Language issues that can be fixed:**

For the options, under:

> How many items per cycle
>  _“Value 0 (zero) means all images togheter in one chunk.”_

change to **together**

> _How long does process lasts_

to **last**

> _NOTE: Defining too long periods can create problems to server availability.
> Do not set periods higherer than 10 secs._

NOTE: Defining too long **of** periods can create problems to server availability.
Do not set periods **higher** than 10 secs.

> _NOTE: If not stopped within this period of secs, process proceed on next page.
> If some sized image production goes wrong, process try to stop by itself._

NOTE: If not stopped within this period of secs, process **proceeds** on **the** next page.
If some sized image production goes wrong, process **tries** to stop by itself.


**On the Cache images page-**

> _How many items has to be processed every cicle. Value 0 (zero) means all images togheter in one chunk. It can be used to review and control all the sizes toghether, when they are already cached._

How many items has to be processed every **cycle**. Value 0 (zero) means all images **together** in one chunk. It can be used to review and control all the sizes **together**, when they are already cached.


The following are both problems with regular cacheManager, so just noting they still exist.

Trying default chunks of 20, it errors out on my live server when using cURL:

> Content Encoding Error
> 
> An error occurred during a connection to -.com.
> 
>     Please contact the website owners to inform them of this problem.
> 

If using classic, it appears to be done rather quickly, but the page will lock up and many of the thumbs will not actually load.


Thanks again for doing this. The ability to limit cacheManager to manageable chunks is a big improvement for limited servers.

**Comment by FilippoBoscarino** [comment]
Hi JesseHC.
Thanks for your contribute.
Please follow the suggestion to repost in the plugin repository, so I can better track the issues
