### ISSUE TITLE
flag_thumbnail.php hardcoded positioning

### ISSUE THREAD

**Issue by FilippoBoscarino** [zenphoto/zenphoto#1379]
I find out that there is an hardcoded positioning of the icons for the library in flag_thmbnail.php that maybe should be moved to css, to  let producing templates be easier.
There are four occurrences similar to this line: 

`$html .= '<img src="' . $img . '" class="imageasflag" alt="" style="position: absolute;top: 4px;left: 4px;"/>' . "\n";`

in the code.
Cheers

**Comment by acrylian** [comment]
You can actually override that via theme CSS already if you use the `!important` keyword on the class. I know that should be avoided but sometimes it is necessary due to the cascade.

Actually this is meant to work out of the box and we didn't want to add extra CSS be it via `<style>` or even an extra file for just this.

We have for sure old grown stuff like this in lots of other places. This is all for later and will nto be changed in v1.6+ anymore.

**Comment by FilippoBoscarino** [comment]
Sorry, I did not mention that it was a suggestion for 2.0
I know the value can be override by !important tag, but you know better than me that is now the best way.
I like very much your CMS and it could be my wish to have it more and more clean and robust through next releases.
In any case feel free to receipt the notice or not, based on your priorities.
Cheers

**Comment by acrylian** [comment]
> Sorry, I did not mention that it was a suggestion for 2.0
> I like very much your CMS and it could be my wish to have it more and more clean and robust through next releases.

Okay, thanks, great. I appreaciate it. We really want to cleanup a lot, especially the backend HTML/CSS will be completely rewritten and get a new layout (we even still have "stone age" table layouts, yeah…) 

The next release is developed in a separate repo. Not yet public as we are not far enough because 1.x always gets in the way. Perhaps let's keep the tickets here for actual bugs for now and save "nice to haves" for later once we manage to go public with the next one.

**Comment by acrylian** [comment]
Added a pragmatic quick fix with an option to  disable the default inline styles and also added individual classes to each flag type so they can be addressed better via custom theme CSS.
