### ISSUE TITLE
If you move or rename a folder or file in Zenphoto, the image cache is not changed

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1380]
If you move or rename a folder or file in Zenphoto, the image cache is not changed and has to be recreated from scratch. This can be impractical, or even impossible, on many shared hosting plans. This also creates many duplicate files or folders that have to be cleaned up.

I know that each album can have a “Cache album images” option with Cache manager active, but that has to be run manually each time a change is made, and again can be slow or impossible on servers with limited resources.

I also know that Cache manager has a “Cleanup image cache sizes” option on the Overview tab, but that seems to be aimed at uninstalled or inactive themes and plugins, and has to be manually run each time changes are made. It also does not work to remove old duplicates.

If you manually try to rename or move the image cache files, which would be a major pain, all of the larger symlink images created by Cache manager would not work. 

XMP files are renamed and moved along with folders, it would be nice if that was also done to the image cache, along with updating links for larger files in the cache. This could save a lot of time for users and massively reduce duplicate files.

Thanks!

P.S.-
While looking into this issue, I noticed a bug report I previously posted that also dealt with cruft left over in the cache while making changes in Zenphoto-
[Turning on Obscure cache filenames does not rename existing cache files, but recreates them all](https://github.com/zenphoto/zenphoto/issues/1295)

**Comment by acrylian** [comment]
> I also know that Cache manager has a “Cleanup image cache sizes” option on the Overview tab, but that seems to be aimed at uninstalled or inactive themes and plugins, and has to be manually run each time changes are made. It also does not work to remove old duplicates.

That is correct, it does (or tries to) remove size registrations, not the images itself. Doing that would be basically the same task as pre-caching as everything would have to processed. 

This is all because the default behaviour that pre-caching is not really considered "necessary". Copying cached files to the right cache folder is actually a good idea. Will take a look.

**Comment by acrylian** [comment]
1.6.1a as updates for this now. Symlinks in the cache should/are also copied if you move/copy an image. They are however not if you move/copy an entire album because we do exactly that and don't process every single image. That would be necessary to fix symlinks here but creates a lot overhead on large albums pssible even containing subalbums. This however create real cached images instead of symlinks.

Btw, we will soon introduce a way to disable symlink via the config file to make the image cache better portable.
