### ISSUE TITLE
Interaction with "no_show v1.4.3" plugin

### ISSUE THREAD

**Issue by FilippoBoscarino** [zenphoto/zenphoto#1384]
I really don't know if it can be considered a bug... due to the fact that this plugin is not officially supported.
Anyway, the plugin exist and I think is used, so I share the point that maybe could be addressed easily.

Using the plugin "no_show v1.4.3" (where I only substitute getShow() to isPublished() not to incur in deprecation error), if you got an unpublished Album in your gallery, and you're browsing the frontend logged as Administrator, when your template is trying to obtain AlbumBase->getAlbumThumbImage() for the unpublished album, it generates an error in log.

I analyzed the point and discover that the error is generated by the condition:
`!$xalbum->exists==true` at line 106 of class-image.php file

This is basically due to the fact that plugin is rather Taliban to define unpublished albums, I know...
But I am wondering if this condition could be relaxed and better specified, not to have this annoying and confusing error in log, expecially when debugging templates development, and permit to continue to use plugin.

The same issue does not happen of unpublished images, because they are hidden also to Admins (...!!!)
I think that something in the logic has been introduced passing from getShow() to isPublished(), because the earlier behaviour was surely different (both unpublished albums and images were showed to Admins and hidden to Users in frontend).

After all Publishing/Unpublishing of objects is managed by the platform, but strangely it does not affect the presentation or not of the object itself to users, and this plugin is the only known solution right now to obtain this result.

**Comment by acrylian** [comment]
The plugin is old and clearly unsupported for years now. So it is not really expected to still work correctly. You should open a ticket on the unsupported repository instead of here.

Quickly to these: 

> The same issue does not happen of unpublished images, because they are hidden also to Admins (...!!!)

Zenphoto's behaviour is (and always was) that If you are an logged in user with a certain rights level you see unpublished items on the fronend like published ones. But you can access unpublished items if you know the direct link.

>  something in the logic has been introduced passing from getShow() to isPublished(),

Both are the same, getPublished() is just an alias with the better understandable name that checks if the item itself is published (the show field = 1). However we did work on the rights management stuff  as things were not correctly handled in the past. I don't remember.

We may introduce an official "private" status to items in the future.
