### ISSUE TITLE
favoritesHandler plugin: general issues

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1421]
If favoritesHandler is used in multi mode - each collection gets a [multi collection nickname], which is added in brackets  to links and buttons.

Opening bracket has no space between it and Link text or title, which results in text clumped together:
![Screenshot_2](https://github.com/zenphoto/zenphoto/assets/75898540/72fa475e-dbb1-486f-a07d-39b8ff61d16f)

Possible solution is to add trailing space after Link text and Title in plugin Options, but this feels untidy and doesn't affect buttons to add/remove from collection.
![Screenshot_3](https://github.com/zenphoto/zenphoto/assets/75898540/06c263ee-cf50-4cca-82e0-84430eb024ba)

**Comment by acrylian** [comment]
I have added space before the set name brackets for now.

Actually I think instead of just printing a link we should have another function to print a intro headlin with a  whole `<ul>` list always so we have by default what you do in the theme. Then we can just use the set name without the extra "My favorites" before it because what else than a favorites set it would it be then.

The interface to add to more than one existing set is also quite a bit inconvenient but that's something for later…

**Comment by kuz-z-zma** [comment]
> what else than a favorites set it would it be then

My favourites. :)
or Collections!

**Comment by acrylian** [comment]
> My favourites. :)
 > or Collections!

Of course. I was actually referring to that if we always print a list like this (no matter if one or more sets/collections):

My Favorites
- Favorites default
- Custom collection

Then the set names do not need to mention "favorites" again ;)

**Comment by bic-ed** [comment]
Ok, this is the right ticket, I report here as a reminder what I found to be wrong (and possibly i already fixed) in the favorites extension:
#### Cosmetic
- Missing space before set name in page title
- Missing space before set name in Add/Remove button
- A typo in printFavoritesURL() (code cosmetic)
#### Functionality
- Instance differing only in letter case should be treated as the same instance, since both option in database and tag_suggest are case insensitive
- Adding a new favorite to an instance may create a duplicate entry of the same instance in the database
- In admin panel, the "Watchers" list generated by the plugin is a raw serialized string
- The page count from pageCount(), for 'checkPageValidity', 'favorites::pageCount' is returning a wrong value under some circumstances
- Missing instance in head title

#### Fatal
- The redirecting after removal of a favorite if the page is no more existing uses $this inside a static function, leading to a fatal error.

**Comment by acrylian** [comment]
Actually a new one your also have been okay. And perhaps you should also re-open it ;-)

**Comment by acrylian** [comment]
Regarding the instance case which is probably the set name?  (sorry, not that familiar with all details off hand). If it makes a difference depends if the database is defined as case sensitive (most are not). So in any case we should have all in lowercase anyway I guess.

**Comment by acrylian** [comment]
I moved the missing head title to the "cosmetic" list because we have no actual SEO relevance as favorites are not public.

**Comment by acrylian** [comment]
> Regarding the instance case which is probably the set name? (sorry, not that familiar with all details off hand). If it makes a difference depends if the database is defined as case sensitive (most are not). So in any case we should have all in lowercase anyway I guess.

This really needs to be check if those are duplicate. Array indexes are also case sensitive. We change this it may break existing things.

**Comment by bic-ed** [comment]
> Regarding the instance case which is probably the set name? (sorry, not that familiar with all details off hand). If it makes a difference depends if the database is defined as case sensitive (most are not). So in any case we should have all in lowercase anyway I guess.
Yes, the set name. I fixed it by using, on post, an existing instance if the newly posted one differs only in uppercase or lowercase letters.

**Comment by bic-ed** [comment]
But the duplicating issue is not ending with that, as both addImage() and addAlbum() functions do non check if the newly posted favorite is already present in the database before adding the new one. The new one will have an identical entry in the db but for the ID only.

**Comment by acrylian** [comment]
Yes it always would have to be made lowercase in the future whereever it is used. I see the possible duplication issue. Would not be complicated to add a query to check first. This all would need some testing especially regarding the lowercase and it must be documented.

**Comment by bic-ed** [comment]
In my fix, when you first add a new set, the case is not relevant. Then, if you try to add a new set which differs only for uppercase or lowercase letters, it is converted to the existing one. 

Probably I should push to my fork the commit with all the fixes, so we can discuss them there before opening a pr here, as there are things that possibly can be achieved in a better way, though they are working to my eyes so far.

**Comment by bic-ed** [comment]
> In my fix, when you first add a new set, the case is not relevant. Then, if you try to add a new set which differs only for uppercase or lowercase letters, it is converted to the existing one.

I did it this way to left the chance to use title case for sets

**Comment by acrylian** [comment]
In general   the case should consistenlty not matter right from the start and be converted to lowercase. However we need to check side effects with existing mixed named sets. Yes, best to look at the code itself.

**Comment by bic-ed** [comment]
> In general the case should consistenlty not matter right from the start and be converted to lowercase. However we need to check side effects with existing mixed named sets. 

That also takes care of existing set, as they continue to function seamlessly after my proposed fix.

**Comment by bic-ed** [comment]
> Yes, best to look at the code itself.

https://github.com/bic-ed/zenphoto/commit/ea2857b438e257236bff0abfa8f4ce8495509718

The description is temporary :-)

**Comment by bic-ed** [comment]
I'm commenting on the committed code, I don't know if you get notified though.
