### ISSUE TITLE
related_item plugin & gettext

### ISSUE THREAD

**Issue by RolandTi** [zenphoto/zenphoto#1429]
Hello !
I'm not sure, but I think the translation for the `<h3>` is not working.
News is not replaced by _Actualités_. And iI don't see any string for 'all'

https://github.com/zenphoto/zenphoto/blob/ea453733716d840a718826268909b00913e68ba4/zp-core/zp-extensions/related_items.php#L161

https://github.com/zenphoto/zenphoto/blob/ea453733716d840a718826268909b00913e68ba4/zp-core/zp-extensions/related_items.php#L155

The $label variable is going nowhere after ? And there sould be also a `'all' => gettext('All')` string.

Thanks for your help !

**Comment by acrylian** [comment]
Yes, the first is indeed a mistake and it should use the $label array. Probably we should also have the array have the full text like "Related news" etc so it is also more clear in the translation. 

I don't think that there should be a label for all in generally because the type only makes sense if you have limited it. No visitor will understand the "all" part unless familiar with all the types I think.

**Comment by acrylian** [comment]
I made a change. Indeed having an "all" index in the $label array is a good idea but I choose to just use a general "Related".

**Comment by RolandTi** [comment]
To me, it's perfect that way. Thanks for your change.
