### ISSUE TITLE
comment_form: mismatched names, id for fields

### ISSUE THREAD

**Issue by kuz-z-zma** [zenphoto/zenphoto#1443]
Currently there is a mismatch in comment_form for input fields names and ids + label for names.
Some fields have "0-" prefix, some don't and for some names and ids don't match.

![Screenshot_47](https://github.com/zenphoto/zenphoto/assets/75898540/8c0e035d-1fed-4ae8-a9e7-da469b28a179)

**Comment by acrylian** [comment]
Actually the "for" attribute is even unnecessary as the label should just enclose the input element right away. IDs and names of course must not match technically but it would be cleaner indeed. 

I don't remember why there is a "0-" at the beginning (which would be even invalide pre-HTML 5). We have that in other forms for legacy reasons instead of proper arrays which at some point will be reworked.

**Comment by acrylian** [comment]
I will take care of these later.

**Comment by acrylian** [comment]
I have updated them. The weird "0-" at the beginning o the names hardcoded within the comment handling. Probably unnecessary but I will not touch this that this time.
