### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by hbredin** [zenphoto/zenphoto#695]
Is there any plan on creating a http://www.docker.io/ image with pre-installed zenphoto?

**Comment by thany** [comment]
Just a small bump :)

Docker has become a big thing in professional CI environments, and it makes a lot of sense even on your average Joe's webserver. It's so darn easy to get a docker image up & running.

I mean, how would like like to condense your installation guide from what it is now, to literally just 1 command? Seriously, that's all it takes.

The reason I'm bumping it, is because it makes sense if the folks over at Zenphoto would maintain a docker, so that official releases can easily go hand-in-hand with their respective docker image updates. It also means docker images become supported. And that support becomes super easy, because you (as the developer) will know exactly what software zenphoto is running on top of. Not only that, it will even be the same for everyone who chooses the docker impplementation.

I see nothing but advantages, but a third-party docker image is always a little bit so-so in my experience.

**Comment by acrylian** [comment]
Bumping does not help ;-) I am sure it might be a useful tool to some like many other tools out there. But I still neither ever used it nor do I have any use for it. So I won't invest any of my low time resources into it.

If you find this really useful and want it you are welcome to provide, maintain and support it as a 3rd party solution.

**Comment by thany** [comment]
If I were to do that (which I very likely might), I think what I'm going to need is a direct download link to the latest release that's always exactly the same url. Not sure yet, but I'll open a new ticket when I need something.

**Comment by acrylian** [comment]
Can't you just use the GitHub api to get the download url to the latest release?

**Comment by thany** [comment]
Not sure yet. The classic "download an unzip" method is fiddly, because it *has* to be a fully automated/unattended install.

**Comment by emieza** [comment]
I created an image in emieza/zenphoto just in case someone is interested

**Comment by acrylian** [comment]
We actually already list it on our site's extensions section : https://www.zenphoto.org/news/docker-zenphoto/

**Comment by benderstwin** [comment]
> I created an image in emieza/zenphoto just in case someone is interested

emieza, I'm using this container on Unraid.  Does it make sense to add imagick?

**Comment by thany** [comment]
@benderstwin It would make sense to add graphicsmagic as well, as an option. Graphicsmagick is faster and less resource-hungry, but I'm sure it has some disadvantages too.

**Comment by acrylian** [comment]
Zenphoto does not support Graphicsmagick

**Comment by thany** [comment]
Really? I think I had it working at one point... Maybe that's happened in a previous life then or something :)
