### ISSUE TITLE
zpErrorHandler() has wrong definition

### ISSUE THREAD

**Issue by mricric** [zenphoto/zenphoto#883]
zpErrorHandler() has wrong definition.
4 arguments defined but 5 are needed by code or function fails.

ex.
zpErrorHandler(E_USER_ERROR, "err test", __FILE__, __LINE__);
Fatal error: Call to a member function getCode() on a non-object in [...]zp-core\functions-common.php on line 26

getCode() is an Exception method that is called when there are not 5 arguments passed to function.
Function tests 5 arguments but there are only 4 in definition.
line 18 : function zpErrorHandler($errno, $errstr = '', $errfile = '', $errline = '') {
line 20 : if (func_num_args() == 5) {

The problem is when I fix to following line, ZP simply stops working and returns blank page.
line 20 : if (func_num_args() == 4) {

Function works when I add a fake 5th argument.
That is dirty :)

(1) easy dirty fix : update definition.
(2) good fix : change "5" to "4" and find why ZP returns a blank page by doing so.
I do not know how to debug the (2)

Zenphoto 1.4.6 [bbddab7675] 
PHP : 5.4.7

**Comment by mricric** [comment]
Zenphoto 1.4.6 [bbddab7675] 
PHP : 5.4.7

**Comment by acrylian** [comment]
The purpose of `func_num_args()` is as you know that you can have flexible number of parameters so the number should not be the point. 

The function is never directly used but set as error/exception handler via `set_error_handler()` and `set_exception_handler()`.  

Can you provide a scenario where you noticed the problem? I don't remember to ever had seen any error related to it using Zenphoto. Which does not mean there is none of course but that function, written by a former colleague,  exists like this at least since version 1.4.4.

**Comment by mricric** [comment]
In order to help debug my plugin, I wanted to use an error handler and I think smarter to use existing function rather than writing my own.
Unfortunately the existing function does not work.

I agree that "func_num_args()" returns the number of used arguments, the problem is the code is comparing it with wrong value.
The function definition require 4 arguments, but the function code require it has 5 arguments. Then the test fails.

If I fix the typo in the code (I replace "5" by "4") then ZP simply stops working. I have a blank page.
Unfortunately I am not good enough to debug why the function mail ZP fail.

**Comment by mricric** [comment]
After going deeper in the code, there is no bug.

I was puzzled by the fact the definition describes 4 args but the code test 5 args.

**Comment by acrylian** [comment]
Ok, thanks.
