### ISSUE TITLE
 DownloadList plugin and Https

### ISSUE THREAD

**Issue by toinced** [zenphoto/zenphoto#892]
Hello,
I'm using the downloadlist plugin in my Zenphoto template for download the albums.

I've added the following code to my album page.

<?php printDownloadAlbumZipURL('Download album', $_zp_current_album); ?>

Everything work correctly if i use http, but if i use https the download does not start, the link will be create with "https:\\downloadurl", but the download does not start, if i delete manually the "s" from "https" the download starts.

Zenphoto version: 1.4.6
Template: zpBase

**Comment by toinced** [comment]
Maybe i've found the problem, downloadlist does not work with https when the folder name of the album contain spaces. 

- Folder name "My Album" --> DownloadList not Work in Https 
- Folder name "MyAlbum" --> DownloadList Work in Https 

Ideas for solve the problem?

Thanks

**Comment by sbillard** [comment]
Please set your site to "DEBUG" mode with the mark release plugin. Clear your debug log and run your test. Report back what you find in the debug log.

Alternatively, I can work with you on this, but since I do not have access to a HTTPS capable site I will need you to host the tests.

**Comment by fretzl** [comment]
Managed to turn MAMP into a https server.

I can reproduce the issue. It indeed happens when an album name has a space in it.
@toinced says the download simply won't start. I get a blank page.

Here's the error in the debug log (nothing in the server log)
(the name of the album is `test album`)

USER ERROR: Invalid album instantiation: test%20album does not exist. in .../zp-core/class-album.php on line 1215
trigger_error called from Album->_albumCheck (class-album.php [1215])
from Album->__construct (class-album.php [1186])
from newAlbum (class-album.php [25])
from AlbumZip::create (downloadList.php [379])
from require_once (downloadList.php [627])
from include (index.php [94])
from index.php [28]

**Comment by fretzl** [comment]
That's weird. I now see the same issue on both http and https.

**Comment by acrylian** [comment]
Can you check the database entries? There might be a mismatch as it stores the download url.

**Comment by fretzl** [comment]
Database is fine. No weird entries.
