### ISSUE TITLE
Admin login issue 1.4.7

### ISSUE THREAD

**Issue by wurzel555** [zenphoto/zenphoto#908]
Hi, 

Since upgrading to 1.4.7 I have an issue with the admin login.
Sometimes when I login direct to the admin console using  the direct url I get the standard login box on white background where I login and get redirected to the admin console. But when I log out then try to log back in again I get the login box on a pink background, when I login I do not get redirected to the admin console I get the login box back but the Admin menu appears in the top right corner. 

Sometimes even using the direct admin url results in the pink login screen appearing. It is pot luck which one I get.

here is a screen shot 

http://steveluther.de/login.jpg

Cheers
Steve

**Comment by MarkRH** [comment]
Only odd thing I've noticed is that if I log out while looking at an image or album I am still logged in when I go to /admin.  I have to logout of their as well in order to log back in and see all the non-published albums and such. Never seen the pink background but I am using a customized version of the Garland theme. What theme are you using?

**Comment by acrylian** [comment]
@MarkRH: I have seen the not really logged out issue before but I always thought that is a Safari issue as I never noticed it in Firefox. I don't remember to have seen the pink page unless you use the login link some themes print in the sidebar. The plain url `<install>/admin` should not lead there.
