### ISSUE TITLE
Code indentation

### ISSUE THREAD

**Issue by SubJunk** [zenphoto/zenphoto#917]
Recently there have been a lot of indentation changes between tabs and spaces, mostly where it used to have tab-indentation and now it's 2-space indents.
It seems very inconsistent, often with both types of indentation existing in the same function.
It's not a big deal at all but I thought I'd mention it since it does create unnecessary merging conflicts for those of us managing forks/branches.

For what it's worth, the previous indentation method of using tabs is what I prefer, since most code editors let you customize how wide tabs are - if someone wants the appearance of 2-space indentation they can set the program to display tabs like that instead of actually replacing all of the tabs with spaces.

**Comment by acrylian** [comment]
Thanks, yes, strangely it is. Somehow a lot code parts are not formatted well but I don't know exactly why. As we (well, now I) always used Eclipse and now NetBeans – and  for the quick edit inbetween TextWrangler – to format the code using tabs. 

We do correct these when working on parts, especially since NetBeans and other tools don't work well with PHP/HTML/JS code mixes causing even worse formatting at time. So those have to be done manually.

**Comment by acrylian** [comment]
Small update, I checked my NetBeans settings and somehow it seem to have reverted a setting without me noticing. Maybe after an update so it did use spaces instead of tabs. Well, both looks the same so I never noticed. It hopefully does this correct from now on. Still code will need re-formatting.

**Comment by acrylian** [comment]
Closed as not a "bug" per se and changed on the go anyway.
