### ISSUE TITLE
suggestion for the controlLink function 

### ISSUE THREAD

**Issue by rb26** [zenphoto/zenphoto#982]
bonjour
controlLink in mobileTheme.php permit to switch from mobile theme to web display (and reverse), but  it opens the default accueil page.
for opening the same page in mobile or normal, I add a parameter in this function:
`controlLink($text=NULL, $before=NULL, $after=Null, $parametres=Null )`

and add this code:
` if (!is_null($parametres)){ $param=str_replace(array("mobileTheme=on&","mobileTheme=off&"),"", $parametres);
				 $enable.='&'.$param;}`

then I can pass the page to linked with:
`mobileTheme::controlLink('Visiter en Mode Mobile',' ~ [ ',' ]',$_SERVER['QUERY_STRING'] );`

it runs correctly, but perhaps a better way??
rb

**Comment by acrylian** [comment]
Have to admit this is once again a function/feature I never used myself. We will take a look.

Best practice is of course not use a responsive website where this would be not necessary but of course our official themes are not yet ready for this. But it is coming.

**Comment by acrylian** [comment]
I took a quick look and I think there is a better way via the object model as we actually do know on what page we actually are. No need to use the `$_SERVER`.

That will assume though that for example the same custom pages exists in both themes chosen. For example the contact page some themes have. Or that both themes chosen have full support for the Zenpage CMS plugin. Otherwise you could run into 404 error pages possibly.

**Comment by acrylian** [comment]
I could only reproduce your issue with mod_rewrite (nice urls) disabled which I actually think nowadays should be the exception.
