### ISSUE TITLE
improvement : back to the right page number

### ISSUE THREAD

**Issue by vincent3569** [zenphoto/zenphoto#985]
hi
on gallery page, if there are few pages of albums (3 for example), and when you visit an album on the 2nd or 3rd page), zenphoto offers a correct back link to the correct page.

this function doesn't exist on news pages.
on the 2nd page of news, if you visit a news, the back link on news goes to the first page.

in the same way, this function doesn't exist on subalbum pages.
on the 2nd page of subalbum, if you visit an album, the back link on album goes to the first page.

it would be a nice improvement to have the same behavior between news, subalbum  and albums

**Comment by acrylian** [comment]
The support build has a change so you also return to the right page from single article pages. It however requires a minor theme change because to make it easy `printZenpageItemsBreadcrumb()` incorporates the news index url now. Basically you have to remove `printNewsIndexURL()` from `news.php` and `pages.php`. Otherwise you get a double "news" in the breadcrumb.
