### ISSUE TITLE
If you enable Imagick on 1.4.12 your locale will fail

### ISSUE THREAD

**Issue by JatB** [zenphoto/zenphoto#997]
I noticed something strange after I enabled Imagick support, my locale failed. When I had it running the default GD, everything was fine-
![imagick turned off - locale okay](https://cloud.githubusercontent.com/assets/10157440/13899944/93dc1c1e-edb7-11e5-8951-26d0c7e9f10e.png)

When I enabled Imagick, my locale immediately failed-
![imagick turned on - locale setting has failed](https://cloud.githubusercontent.com/assets/10157440/13899953/adce6ac8-edb7-11e5-9cdd-52d7c928225c.png)

Running setup again with Imagick turned on, I get this error-
_"Warn: PHP setlocale() failed Locale functionality is not implemented on your platform or the specified locale does not exist. Language translation may not work.See the user guide on zenphoto.org for details."_

Turning Imagick off again, the locale immediately comes back, and setup runs fine (besides a filesystem error I always get with my hosting plan).

Looking through the logs, the previous error is the only one I get. All of my main server info is in the images, and here is some more detailed info for Imagick if that helps-
![imagick php info](https://cloud.githubusercontent.com/assets/10157440/13899973/4954d4a0-edb8-11e5-9c6a-e305d7823122.png)

I'm currently running this on a shared hosting plan with Host Gator. Let me know if you need anymore info.

**Comment by acrylian** [comment]
Weird, the local should have nothing to do with the image library. This might be something specific to your host. Maybe you can contact them? I can't reproduce it on my server which is also just a shared hosting plan:

![bildschirmfoto 2016-03-19 um 18 46 46](https://cloud.githubusercontent.com/assets/2474309/13900291/294b986a-ee03-11e5-9ff2-c2266cdd93bf.jpg)

**Comment by fretzl** [comment]
Can't reproduce it either.

**Comment by JatB** [comment]
Weird. I just tried it on a completely separate account, still on Host Gator, but with a 1.4.8 install and it failed there as well. I’ll contact their tech support and see if they can provide any info.

**Comment by JatB** [comment]
After weeks of getting no help from their tech support, I was able to escalate the support ticket and get someone that would actually look into the issue. This is their response (with my personal server info removed)-


> Hello,
> 
> I was able to replicate the error setting locale in Zenphoto.  After much investigation the only related information I can find for this error is a bug report for PHP when using setlocale and passing a float number with imagick.
> 
> https://bugs.php.net/bug.php?id=59571
> 
> There are 38 files in the zenphoto installation that references the setlocale function.
> 
> # grep -rli 'setlocale' * | wc -l
> 38
> 
> The locales are all available on your server, and Imagick is working as expected.
> 
> # locale -a | grep -i en_us
> en_US
> en_US.iso88591
> en_US.iso885915
> en_US.utf8
> 
> However, the way that the Zenphoto software is interacting with imagick on this server is what is causing the error.  While we are happy to help where we can, and strive to provide excellent support, we are not developers, and are unable to provide a specific cause for Zenphoto's software throwing the error, even after extensively sifting through their code.  
> 
> Though this particular setting in Zenphoto does not throw an error on other servers, this does detract from the developers of Zenphoto being the best individuals able to identify issues with their code interactions.  I would recommend providing this bug regarding setlocale to the Zenphoto developers.  
> 
> If you receive more information regarding this error that you believe we are able to assist with, please don't hesitate to contact us.
>

**Comment by acrylian** [comment]
This is really weird and really sounds like a Imagick bug to me… 

Since we cannot reproduce ist, I fear we will need your help with this. So what you would need to try is to set the locale like the last comment on that link suggests somehow.

**Comment by JatB** [comment]
If you have any idea on how exactly to test it out, I’m more than willing to try.

One thing I did notice on other systems I successfully tested it on was that the version of ImageMagick that was running was much newer. The version Host Gator is running (6.7.6-8) is over four years old (http://git.imagemagick.org/repos/ImageMagick/blob/ImageMagick-6/ChangeLog).

The PHP wrapper, Imagick is currently on 3.4.1 and they are running 3.1.0RC2 on their default PHP, which is a beta and again from four years ago (https://pecl.php.net/package/imagick). Changing from the default 5.4 to PHP 5.5 or 5.6 only changes Imagick to 3.1.2, which is still almost three years old, and leaves the main ImageMagick at over four years old.

I asked their techs about upgrading and they said they have no plans to update.

That said, both versions of Imagick display the locale error, and all versions are officially supported by Zenphoto.

Also, going over these versions it looks like you might need to update your documentation.

Your Server requirements state-
“Imagick graphics libary 6.3.8/Imagick 2.1.0”
http://www.zenphoto.org/news/installation-and-upgrading/#server-requirements

But lib-Imagick.php in 1.4.12 states-
“Requires Imagick 3.0.0+ and ImageMagick 6.3.8+”

**Comment by JatB** [comment]
I also found this very old issue where setlocale in ImageMagick would cause locale issues in an application. The issue was supposedly fixed years ago, but I’m passing it along if it helps in any way- https://www.imagemagick.org/discourse-server/viewtopic.php?t=10656

**Comment by sbillard** [comment]
You can possibly gain more information by setting the define for "DEBUG_LOCALE" to true. This will log the actions taken for setting the locale.

https://bugs.php.net/bug.php?id=59571 is unlikely to be related. This represents a problem in Imagick because of the number formatting--using a comma as the decimal separator. That will not happen for the en_US locales.

Post the results of the Locale debugging and maybe they will shed some light.

**Comment by acrylian** [comment]
@JatB Thanks for the note, I have updated the server requirements.

**Comment by JatB** [comment]
Okay, here's what I get when I set "DEBUG_LOCALE" to true and enable Imagick, which causes the locale to fail-
[debug - enabling Imagick - locale fails.zip](https://github.com/zenphoto/zenphoto/files/275852/debug.-.enabling.Imagick.-.locale.fails.zip)

Here's what I get when I disable Imagick and locale goes back to working.
[debug - disabling Imagick - locale works.zip](https://github.com/zenphoto/zenphoto/files/275853/debug.-.disabling.Imagick.-.locale.works.zip)

**Comment by sbillard** [comment]
What this shows is that indeed the setLocale() PHP function is "failing." That is, it is returning False or an empty string. According to the PHP documentation the function returns  "FALSE if the locale functionality is not implemented on your platform, the specified locale does not exist or the category name is invalid."

Since this works with Imagick disabled we can presume that the locale and category are normally valid and implemented. Also since this is (to the PHP script) a monotonic operation we have to assume that Imagick has somehow disabled the setLocale() functionality.

It would be interesting to see what happens if the setLocale() call is done before the Imagick library is loaded then just after it has been loaded. You could try this by inserting 

	
var_dump(setlocale(LC_ALL, array('en_US.UTF8','en_US.UTF-8','en_US.@euro','en_US','en',NULL)));
		
Just before and after the code that loads the graphics library

while (!function_exists('zp_graphicsLibInfo')) {
	require_once(dirname(__FILE__) . '/' . array_shift($try));
}

This is line 220 of functions-basic.php in the current version of ZenPhoto20.

I am assuming it will show "en_US.UTF8" for the before and FALSE for the after. If so, pretty much nothing that the zenphoto scripts can do about it other than seeing if the locale setup can be moved to before the graphics library setup.

**Comment by JatB** [comment]
If I enabled the code before I got- 
string(10) "en_US.UTF8"
to show up on the page before anything else, or just that, with Imagick both enabled and disabled.

When I enabled the code after with Imagick disabled, I got the same-
string(10) "en_US.UTF8"
**_BUT_** with Imagick enabled, I got-
string(1) "C"
at the top of the gallery page when I refreshed.

I'm not a programmer, but maybe there is a way to add an additional check it the locale is returning as "C" instead of something specific?

I don't think you wanted this, but I also tried it with the code both before and after with Imagick turned off, all that would be displayed on the page for both the Admin page and gallery page was-
string(10) "en_US.UTF8"
string(10) "en_US.UTF8"

If I reset it, and enabled the code again both before and after, then Imagick, I would get the same code (now with the rest of the gallery page) first thing after <body>
string(10) "en_US.UTF8"
string(10) "en_US.UTF8"

I’ve attached debug text for all versions. Sometimes when the page would only load the string text, I would copy whatever debug was left after I reset the code. I also enabled DEBUG_404 in case that might help with the locale info. The only thing I removed was my personal server info.

As always thanks for your attention.
[debug with code.zip](https://github.com/zenphoto/zenphoto/files/276287/debug.with.code.zip)

**Comment by sbillard** [comment]
Unfortunately, at least for non-English locales it is important that the locale be set correctly else the translations do not work. For English it does not matter since the default language is English.

Imagick is setting the locale to "C" presumably so it's number to string conversion works. Why this is only happening for your installation (so far as we know) is a mystery. But it is also a bug in Imagick. There are locale independent ways to create the decimal numbers--our implementation of Google Maps, for one, does this correctly.

I suspect that if we fix this for the locale then Imagick will fail with bad numeric parameters. But that is just a guess. It might also reset the locale to "C" each time it is called. 

Are you using any languages other than English?

**Comment by JatB** [comment]
On one installation it is just English, on the other it is multiple European languages.

For me personally, it is not the end of the world. I can also go back to using the default GD (even though I really like the quality and memory handling of Imagick). I was just hoping to find a resolution for others that might be having the same problem and not realize the cause.

Thank you all for your time with this.

**Comment by acrylian** [comment]
Really sounds like this is something Imagick and/or PHP bug we cannot really solve. Especially if you use multilingual functionality and therefore gettext then setting the locale is required. 

We can keep it in mind in case it surfaces for others, too.

**Comment by sbillard** [comment]
@JatB: you can also use Imagick and simply ignore the error report. Since you are English only you are not using Locale functionality.
